import type { RegulatoryProfile } from "../regulatory-data";

export const REGULATORY_PROFILES_LATAM: Record<string, RegulatoryProfile> = {
  "CO": {
    country: "Colombia",
    countryCode: "CO",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "Registro Nacional de Turismo (RNT) — mandatory national tourism registry",
      typicalTimeline: "1-3 months for RNT; additional 1-2 months for local permits",
      renewalFrequency: "Annual renewal of RNT",
      estimatedCost: "$200-$1,000 (RNT); municipal permits vary",
      notes: "RNT is administered by MinCIT (Ministerio de Comercio, Industria y Turismo). All hospitality establishments must register before operating. Failure to register carries fines. Medellín and Cartagena have additional local requirements. Curaduría Urbana approval needed for construction/renovation.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "2-6 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "POT (Plan de Ordenamiento Territorial) governs zoning in each municipality. Medellín: check current POT land use designation — some residential areas allow mixed-use. Cartagena: UNESCO World Heritage Site in the walled city — strict heritage controls via PEMP (Plan Especial de Manejo y Protección). Environmental license from ANLA may be required for larger projects.",
    },
    buildingCodes: {
      fireCodeStandard: "NSR-10 (Normas Colombianas de Diseño y Construcción Sismo Resistente) + NFPA adapted standards",
      adaEquivalent: "NTC 6047 (Norma Técnica Colombiana — accessibility for built environment)",
      seismicRequirements: true,
      energyEfficiencyCode: "RUES (Reglamento de Uso Eficiente de Energía) — relatively new, enforcement varies",
      maxOccupancyRegulation: "Determined by local fire department (Bomberos) inspection",
      notes: "Colombia is in a high seismic zone — NSR-10 compliance is mandatory and strictly enforced. Medellín (Zone Alta) and surrounding areas require robust seismic design. All buildings require a construction license (Licencia de Construcción) from the local Curaduría Urbana.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No restrictions on foreign ownership of real property. Equal treatment under Ley 9 de 1991. Must register investment with Banco de la República via declaración de cambio.",
      repatriationRestrictions: false,
      treatyProtections: "US-Colombia BIT (2012); Colombia-EU FTA; Pacific Alliance member",
      notes: "Colombia actively encourages foreign investment in tourism. Tax incentives available for new hotel construction (income tax exemption for 20 years under certain conditions — verify current status of Ley 2068 de 2020 tourism incentives). Exchange registration is mandatory for future repatriation of profits.",
    },
    labor: {
      minimumWage: "COP 1,423,500/month (2026) + transportation subsidy COP 200,000/month",
      mandatoryBenefits: "Health insurance (EPS), pension (AFP), workers' comp (ARL), severance (Cesantías), vacation (15 days/year), prima de servicios (13th month equivalent), dotación (uniforms 3x/year for certain salary levels)",
      terminationRules: "Just cause required for termination without severance. Unjust termination triggers indemnización (severance payment based on tenure). Collective dismissal requires Ministry of Labor authorization.",
      unionPrevalence: "Low to moderate in hospitality. Pactos colectivos more common than formal unions in the sector.",
      notes: "Total employer cost of mandatory benefits adds approximately 50-55% on top of base salary. Night shift (10pm-6am) carries a 35% surcharge. Sunday/holiday work carries a 75% surcharge. Parafiscales (SENA, ICBF, Caja de Compensación) are additional employer charges.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "https://www.mincit.gov.co/minturismo/registro-nacional-de-turismo",
      "https://www.anla.gov.co/",
      "NSR-10 (Reglamento Colombiano de Construcción Sismo Resistente)",
      "Código Sustantivo del Trabajo (Colombia)",
      "Ley 2068 de 2020 (Ley de Turismo)",
      "https://www.banrep.gov.co/",
    ],
  },

  "CR": {
    country: "Costa Rica",
    countryCode: "CR",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "Declaración Turística (ICT — Instituto Costarricense de Turismo), Patente Municipal, Permiso Sanitario (Ministry of Health)",
      typicalTimeline: "2-4 months for ICT registration; 1-2 months for municipal patent",
      renewalFrequency: "Annual",
      estimatedCost: "$500-$2,000",
      notes: "ICT Declaración Turística provides tourism incentives (tax benefits on imports of equipment). CST (Certificación para la Sostenibilidad Turística) is voluntary but valuable for marketing and may provide additional incentives. Municipality (Municipalidad) patent is mandatory.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-6 months",
      environmentalReviewRequired: true,
      historicPreservation: false,
      notes: "SETENA (Secretaría Técnica Nacional Ambiental) environmental assessment required for most tourism projects. Maritime Zone Law (Ley de Zona Marítimo Terrestre) restricts development within 200m of high-tide line — concessions required. Regulador del Plan Regulador (local zoning plan) governs land use. Many beach areas require concession rather than ownership.",
    },
    buildingCodes: {
      fireCodeStandard: "NFPA standards (widely adopted in Costa Rica); Código Sísmico de Costa Rica 2010",
      adaEquivalent: "Ley 7600 (Ley de Igualdad de Oportunidades para las Personas con Discapacidad)",
      seismicRequirements: true,
      energyEfficiencyCode: "No mandatory national energy code for buildings; voluntary RESET certification gaining traction",
      maxOccupancyRegulation: "Bomberos (fire department) inspection determines occupancy limits",
      notes: "Costa Rica is in a high seismic zone — the 2010 Seismic Code (CSCR-10) is strictly enforced. CFIA (Colegio Federado de Ingenieros y Arquitectos) must approve all construction plans. Licensed Ingeniero Responsable required.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "Foreigners can own property with same rights as citizens (constitutional guarantee). Exception: Maritime Zone (50-200m from coast) requires concession, and concessionaires must be Costa Rican residents or companies with majority Costa Rican ownership. First 50m from coast is public and non-developable.",
      repatriationRestrictions: false,
      treatyProtections: "CAFTA-DR (with US); Costa Rica-EU Association Agreement; numerous BITs",
      notes: "Costa Rica is very welcoming to foreign investment in tourism. Free trade zone (Zona Franca) benefits may apply to certain tourism projects. Pensionado/Rentista visa programs facilitate residency for investors.",
    },
    labor: {
      minimumWage: "CRC 375,000-550,000/month (varies by skill category; hospitality workers are 'calificados')",
      mandatoryBenefits: "CCSS (Caja Costarricense de Seguro Social) — employer ~26.5% of payroll; aguinaldo (13th month), vacation (2 weeks/year), severance (Cesantía — 1 month per year up to 8 years)",
      terminationRules: "Just cause required (Código de Trabajo Art. 81). Unjust termination triggers preaviso (notice pay) + cesantía (severance). Labor courts strongly favor employees.",
      unionPrevalence: "Low in hospitality. Solidarismo (employee associations) more common than unions.",
      notes: "CCSS contributions (~26.5% employer share) are a substantial payroll cost. Overtime: 1.5x after 8 hours. Holiday work at double pay. Thirteen-month salary (aguinaldo) paid in December. Total employer burden approximately 40-45% above base salary.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "https://www.ict.go.cr/",
      "SETENA regulations (Decreto 31849-MINAE-S-MOPT-MAG-MEIC)",
      "Código Sísmico de Costa Rica 2010 (CSCR-10)",
      "Ley 7600 (Accessibility)",
      "Código de Trabajo de Costa Rica",
      "CAFTA-DR text",
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SECONDARY COUNTRIES — good detail
  // ═══════════════════════════════════════════════════════════════════════════

  "BR": {
    country: "Brazil",
    countryCode: "BR",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "Cadastur (Ministry of Tourism mandatory registry), Alvará de Funcionamento (municipal operating license), ANVISA health permits for F&B",
      typicalTimeline: "2-4 months",
      renewalFrequency: "Annual for Alvará; Cadastur renewed every 2 years",
      estimatedCost: "BRL 2,000-10,000",
      notes: "Cadastur registration is mandatory (Lei 11.771/2008). SBClass (Sistema Brasileiro de Classificação de Meios de Hospedagem) star classification is voluntary. Fire department (Corpo de Bombeiros) AVCB certification mandatory. Environmental licensing (IBAMA for federal; state agencies for local) may be required.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-8 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "Municipal Plano Diretor governs zoning. IPHAN (Instituto do Patrimônio Histórico e Artístico Nacional) approval required for listed heritage properties. Environmental licensing (Licença Prévia, Licença de Instalação, Licença de Operação) is a three-stage process that can add significant time. Coastal zone (Zona Costeira) has additional protections under federal law.",
    },
    buildingCodes: {
      fireCodeStandard: "State fire codes (varying by state); ABNT NBR 9077 (emergency exits); Corpo de Bombeiros certification (AVCB/CLCB)",
      adaEquivalent: "ABNT NBR 9050 (Acessibilidade a edificações, mobiliário, espaços e equipamentos urbanos)",
      seismicRequirements: false,
      energyEfficiencyCode: "PROCEL Edifica / PBE Edifica (voluntary energy labeling for commercial buildings)",
      maxOccupancyRegulation: "State fire department (Corpo de Bombeiros) determines based on ABNT standards",
      notes: "Fire codes vary significantly by state — São Paulo, Rio de Janeiro, and Minas Gerais have detailed regulations. AVCB (Auto de Vistoria do Corpo de Bombeiros) is mandatory before any commercial operation. Construction requires ART (Anotação de Responsabilidade Técnica) from a licensed engineer.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "Generally no restrictions on urban real property. Rural property acquisition by foreigners is restricted (Lei 5.709/1971) — limited to certain sizes depending on municipality. CPF/CNPJ registration required.",
      repatriationRestrictions: false,
      treatyProtections: "Brazil has few BITs in force. MERCOSUR investment protocols. No BIT with the US — rely on Brazilian domestic law protections.",
      notes: "Foreign investment must be registered with Banco Central do Brasil (RDE-IED) for repatriation rights. ITBI (property transfer tax) varies by municipality (typically 2-3%). Brazil has high regulatory complexity — experienced local counsel essential. Tax treaty network is limited compared to other Latin American markets.",
    },
    labor: {
      minimumWage: "BRL 1,518/month (2025)",
      mandatoryBenefits: "FGTS (8% employer deposit), INSS (employer ~26.8%), 13th salary, 30 days vacation + 1/3 vacation bonus, vale transporte (transport voucher), vale refeição (meal voucher — common by agreement)",
      terminationRules: "Without just cause: 40% FGTS fine + notice period (up to 90 days for long tenure) + accrued rights. Just cause (Art. 482 CLT) limits severance. Labor court (Justiça do Trabalho) heavily favors employees.",
      unionPrevalence: "Moderate. Mandatory union contribution eliminated in 2017 reform but unions remain active. Hospitality workers organized by state-level unions (Sindicato dos Trabalhadores em Turismo e Hospitalidade).",
      notes: "CLT (Consolidação das Leis do Trabalho) is comprehensive. 2017 reform (Lei 13.467) modernized some rules but core protections remain. Total employer burden approximately 60-70% above base salary — among the highest in Latin America. 'eSocial' digital labor compliance system adds administrative complexity.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "Lei 11.771/2008 (Política Nacional de Turismo)",
      "CLT (Consolidação das Leis do Trabalho)",
      "ABNT NBR 9050 (Accessibility)",
      "https://cadastur.turismo.gov.br/",
    ],
  },

  "DO": {
    country: "Dominican Republic",
    countryCode: "DO",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "MITUR (Ministerio de Turismo) classification and registration, Municipal business license, Health permits",
      typicalTimeline: "2-4 months",
      renewalFrequency: "Annual",
      estimatedCost: "$500-$2,000",
      notes: "CONFOTUR (Consejo de Fomento Turístico) provides significant tax incentives for tourism projects — up to 15 years of income tax and property tax exemptions for qualifying projects. MITUR classification determines star rating. Pro-tourism government policy makes licensing relatively straightforward.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "2-6 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "Municipal land use plans govern zoning. Environmental license required from Ministry of Environment for most tourism projects. Zona Colonial in Santo Domingo has UNESCO heritage protections. Coastal development has additional restrictions under Environmental Law 64-00.",
    },
    buildingCodes: {
      fireCodeStandard: "MOPC (Ministerio de Obras Públicas) regulations; R-001 (Reglamento de Construcciones) references NFPA",
      adaEquivalent: "Ley 5-13 sobre Discapacidad (2013); compliance enforcement varies",
      seismicRequirements: true,
      energyEfficiencyCode: "No mandatory energy efficiency code; voluntary green building initiatives",
      maxOccupancyRegulation: "MOPC and fire department inspection",
      notes: "The Dominican Republic is seismically active (Hispaniola fault zone). R-001 building code is the primary regulation. Hurricane-resistant construction standards are critical. MOPC plan review required for all commercial construction.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No restrictions on foreign ownership. Equal treatment under law. Title registration via Tribunal de Tierras (land court) provides strong title protection.",
      repatriationRestrictions: false,
      treatyProtections: "CAFTA-DR (with US); numerous BITs",
      notes: "CONFOTUR incentives are a major draw — 100% income tax exemption for up to 15 years for qualifying tourism projects. Property transfer tax 3%. Highly favorable foreign investment regime. Title insurance recommended despite improved land registration system.",
    },
    labor: {
      minimumWage: "DOP 15,447-21,000/month (varies by company size and sector; tourism sector rates)",
      mandatoryBenefits: "TSS (Social Security — employer ~14.4%), AFP (pension), SFS (health), ARL (workers' comp), vacation (14 days/year), 13th month (Regalía Pascual), participation in profits (10% of net profits, capped)",
      terminationRules: "Desahucio (termination without cause) permitted with notice and severance (Cesantía — 6 days' salary per year for 1st year, increasing up to 23 days/year for 5+ years). Despido justified termination requires documented cause.",
      unionPrevalence: "Low in hospitality.",
      notes: "Profit sharing (participación de los empleados) at 10% of net profits is mandatory and can be a significant cost. Total employer burden approximately 20-25% above base salary (lower than many Latin American countries). Worker-friendly labor courts.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "Ley 158-01 (CONFOTUR)",
      "Código de Trabajo de la República Dominicana",
      "https://www.mitur.gob.do/",
      "CAFTA-DR text",
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // OTHER COUNTRIES — basic detail
  // ═══════════════════════════════════════════════════════════════════════════

  "AR": {
    country: "Argentina",
    countryCode: "AR",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "Registro de Prestadores Turísticos (national/provincial), Habilitación Municipal (municipal operating license)",
      typicalTimeline: "2-4 months",
      renewalFrequency: "Annual habilitación; tourism registry varies by province",
      estimatedCost: "Varies by province — consult local counsel",
      notes: "Tourism regulation is primarily provincial (23 provinces + CABA each have own tourism laws). National registry through SECTUR (Secretaría de Turismo). Buenos Aires (CABA) has specific regulations under Ley 600 de Turismo.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-8 months (can be significantly longer in Buenos Aires)",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "Código de Planeamiento Urbano governs zoning in Buenos Aires. Provinces have own planning codes. Environmental impact assessment required under Ley General del Ambiente 25.675. Heritage protections in Buenos Aires (San Telmo, La Boca), Salta, and other historic cities.",
    },
    buildingCodes: {
      fireCodeStandard: "IRAM fire safety standards; municipal fire regulations; Bomberos certification",
      adaEquivalent: "Ley 24.314 (accessibility for persons with disabilities); IRAM 11.180",
      seismicRequirements: true,
      energyEfficiencyCode: "IRAM 11.601-11.605 (thermal insulation standards — mandatory in some jurisdictions, recommended in others)",
      maxOccupancyRegulation: "Municipal code and fire department inspection",
      notes: "Western Argentina (Mendoza, San Juan) is a high seismic zone — INPRES-CIRSOC regulations apply. Buenos Aires has moderate seismic requirements. Building permits through municipal Dirección de Obras.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No general restrictions on urban property. Rural land ownership by foreigners limited to 1,000 hectares (Ley 26.737 de Tierras). Border zones may require additional security clearance.",
      repatriationRestrictions: true,
      treatyProtections: "US-Argentina BIT; numerous BITs (though Argentina has a contentious arbitration history)",
      notes: "CRITICAL: Argentina has a history of capital controls (cepo cambiario). As of early 2026, recent liberalization under current government — but verify current exchange control status before investing. Profits and capital repatriation have historically been restricted or required central bank approval. Dollarized financial model mitigates currency risk but does not eliminate transfer risk. Consult current BCRA (Banco Central) regulations.",
    },
    labor: {
      minimumWage: "ARS 271,571/month (subject to frequent adjustments due to inflation; 2025 — verify current rate)",
      mandatoryBenefits: "Employer social security ~27% of gross; 13th salary (SAC/Aguinaldo — 2 half payments); 14-35 days vacation (by tenure); mandatory union obra social (health)",
      terminationRules: "Without cause: 1 month's salary per year of tenure (minimum 2 months). 30-60 day notice or pay in lieu. Labor courts strongly favor workers. Double indemnification decrees have been applied periodically.",
      unionPrevalence: "High. Sector unions (UTHGRA — Unión de Trabajadores del Turismo, Hoteleros y Gastronómicos de la República Argentina) are powerful. Collective bargaining agreements (CCT) set sector minimums well above legal minimum wage.",
      notes: "UTHGRA is one of Argentina's strongest unions. CCT 389/04 governs the hospitality sector. Total employer burden approximately 40-50% above base salary. Inflation-driven wage adjustments are frequent (quarterly or more). Payroll costs highly volatile in peso terms — dollar-adjusted modeling essential.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "Ley Nacional de Turismo 25.997",
      "Ley de Contrato de Trabajo 20.744",
      "BCRA exchange control regulations",
      "UTHGRA CCT 389/04",
    ],
  },

  "SV": {
    country: "El Salvador",
    countryCode: "SV",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "CORSATUR (Corporación Salvadoreña de Turismo) registration, Municipal operating license",
      typicalTimeline: "1-3 months",
      renewalFrequency: "Annual",
      estimatedCost: "$300-$1,500",
      notes: "CORSATUR/MITUR handles tourism classification. Ley de Turismo (2005) governs the sector. Government has actively promoted tourism investment. Bitcoin (BTC) is legal tender alongside USD since 2021 — but practical hospitality operations remain USD-based.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "2-4 months",
      environmentalReviewRequired: true,
      historicPreservation: false,
      notes: "OPAMSS (Oficina de Planificación del Área Metropolitana de San Salvador) governs zoning in the capital region. Environmental permit required from MARN (Ministerio de Medio Ambiente y Recursos Naturales). Outside AMSS, municipal planning rules apply.",
    },
    buildingCodes: {
      fireCodeStandard: "Ley de Urbanismo y Construcción; references NFPA standards; limited enforcement outside urban areas",
      adaEquivalent: "Ley de Equiparación de Oportunidades para las Personas con Discapacidad (2000); limited enforcement",
      seismicRequirements: true,
      energyEfficiencyCode: "No mandatory energy efficiency code",
      maxOccupancyRegulation: "Municipal and fire department assessment",
      notes: "El Salvador is highly seismically active. Norma Especial para Diseño y Construcción (post-2001 earthquakes) applies. Volcanic activity is also a consideration. Construction quality varies significantly — professional engineering oversight essential.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No restrictions on foreign ownership. Ley de Inversiones (1999) guarantees equal treatment. PROESA (export/investment promotion agency) facilitates investment.",
      repatriationRestrictions: false,
      treatyProtections: "CAFTA-DR (with US); US-El Salvador BIT",
      notes: "Dollarized economy (since 2001) eliminates currency risk for USD-denominated investors. Tax incentives available for tourism under Ley de Turismo. Generally investor-friendly regulatory environment.",
    },
    labor: {
      minimumWage: "$365/month for commerce and services sector (2024 — verify current rate)",
      mandatoryBenefits: "ISSS (health — employer 7.5%), AFP (pension — employer 7.75%), aguinaldo (15 days' salary), vacation bonus (30% premium on 15 vacation days)",
      terminationRules: "Just cause or unjust termination with indemnización (30 days' salary per year of service, no cap). Notice period required.",
      unionPrevalence: "Low in hospitality.",
      notes: "Total employer burden approximately 20-25% above base salary. Relatively lower labor costs than other Central American countries. 44-hour workweek standard.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "Ley de Turismo de El Salvador (2005)",
      "Código de Trabajo de El Salvador",
      "CAFTA-DR text",
      "https://www.proesa.gob.sv/",
    ],
  },

  "PA": {
    country: "Panama",
    countryCode: "PA",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "ATP (Autoridad de Turismo de Panamá) registration, Aviso de Operación (municipal), Ministry of Health (MINSA) permit",
      typicalTimeline: "2-4 months",
      renewalFrequency: "Annual",
      estimatedCost: "$500-$2,000",
      notes: "Law 80 of 2012 (Tourism Master Plan) provides substantial incentives. ATP classifies hotels. Zona Libre de Colón has special business rules. Panama City and beach resort areas have streamlined tourism licensing.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "2-6 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "MIVIOT (Ministerio de Vivienda y Ordenamiento Territorial) oversees zoning. Environmental impact assessment through MiAMBIENTE. Casco Antiguo (Panama City old town) is UNESCO World Heritage — strict heritage controls under Oficina del Casco Antiguo.",
    },
    buildingCodes: {
      fireCodeStandard: "REP (Reglamento Estructural Panameño); Cuerpo de Bomberos regulations; NFPA referenced",
      adaEquivalent: "Ley 42 de 1999 (accessibility for persons with disabilities)",
      seismicRequirements: true,
      energyEfficiencyCode: "JTIA (Junta Técnica de Ingeniería y Arquitectura) standards; no specific energy code for existing buildings",
      maxOccupancyRegulation: "Bomberos inspection and JTIA-approved plans",
      notes: "REP 2004 (updated) is the structural code. Panama is in a moderate seismic zone. All construction plans must be reviewed by JTIA-licensed professionals. High-rise construction is common in Panama City — different standards may apply.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No restrictions on foreign ownership of titled (finca) property. ROP (Derechos Posesorios) land has less secure title — titled property strongly recommended. 10km from border requires special permission.",
      repatriationRestrictions: false,
      treatyProtections: "US-Panama TPA (Trade Promotion Agreement); numerous BITs",
      notes: "Panama is a major investment hub. Territorial tax system — only Panama-source income is taxed. Tourism incentives under Law 80 include: 100% income tax exemption for 15 years on tourism activities, import duty exemptions on construction materials and equipment. Effectively dollarized (Balboa pegged 1:1 to USD). Very favorable investment climate.",
    },
    labor: {
      minimumWage: "$500-$700/month (varies by economic activity and region; tourism sector rates)",
      mandatoryBenefits: "CSS (Caja de Seguro Social — employer 12.25%), 13th month (paid in 3 installments), 30 days vacation/year, seniority premium (prima de antigüedad — 1 week/year)",
      terminationRules: "Just cause required for termination without severance. Unjust termination: seniority premium + indemnización (3.4 weeks' salary per year of service). Reinstatement can be ordered.",
      unionPrevalence: "Low in hospitality.",
      notes: "Total employer burden approximately 20-25% above base salary. 13th month paid in thirds (April, August, December). Relatively flexible labor market by Latin American standards.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "Ley 80 de 2012 (Tourism Law)",
      "Código de Trabajo de Panamá",
      "https://www.atp.gob.pa/",
      "US-Panama TPA text",
    ],
  },

  "UY": {
    country: "Uruguay",
    countryCode: "UY",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "MINTUR (Ministerio de Turismo) registration and classification, Municipal habilitación",
      typicalTimeline: "2-4 months",
      renewalFrequency: "Annual",
      estimatedCost: "$500-$2,000",
      notes: "MINTUR classifies all accommodation establishments. Ley de Turismo 19.253 governs the sector. Uruguay is known for regulatory transparency and strong rule of law — licensing is relatively straightforward.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-6 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "Municipal Intendencia governs zoning. DINAMA (Dirección Nacional de Medio Ambiente) environmental assessment required for tourism projects. Colonia del Sacramento has UNESCO heritage protections. Coastal development (especially Punta del Este area) has specific regulations.",
    },
    buildingCodes: {
      fireCodeStandard: "Dirección Nacional de Bomberos regulations; municipal fire safety codes",
      adaEquivalent: "Ley 18.651 (Protección Integral de Personas con Discapacidad, 2010)",
      seismicRequirements: false,
      energyEfficiencyCode: "No mandatory energy efficiency code for existing buildings; emerging standards for new construction",
      maxOccupancyRegulation: "Bomberos (fire department) and municipal inspection",
      notes: "Uruguay has low seismic risk. Building permits through municipal Intendencia. Construction standards are generally high but vary by municipality. Professional engineering/architecture sign-off required.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No restrictions on foreign ownership. Equal treatment guaranteed by constitution. No minimum investment requirements.",
      repatriationRestrictions: false,
      treatyProtections: "US-Uruguay BIT; MERCOSUR investment protocols; numerous BITs",
      notes: "Uruguay is considered the most stable and transparent market in South America. Free trade zones (Zonas Francas) offer tax benefits for qualifying activities. Investment promotion through Uruguay XXI. Strong property rights protection and independent judiciary. No exchange controls.",
    },
    labor: {
      minimumWage: "UYU 22,268/month (2025 — adjusted periodically)",
      mandatoryBenefits: "BPS (employer social security ~12.63%), aguinaldo (13th month — 2 half payments), 20 days vacation (increasing with tenure), sick leave",
      terminationRules: "No just cause requirement — employer can terminate with notice and severance (despido común). Severance: 1 month per year of service up to 6 months. Minimal notice period.",
      unionPrevalence: "Moderate. PIT-CNT federation represents workers. Consejos de Salarios (tripartite wage councils) set sector minimums.",
      notes: "Uruguay's Consejos de Salarios system sets wages by sector through negotiation between government, employers, and unions. Hospitality sector (Grupo 14) has its own wage council. Total employer burden approximately 20-25% above base salary. Relatively flexible termination compared to other Latin American countries.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "Ley 19.253 (Tourism Law)",
      "https://www.gub.uy/ministerio-turismo/",
      "BPS regulations",
      "US-Uruguay BIT",
    ],
  },

  "PE": {
    country: "Peru",
    countryCode: "PE",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "MINCETUR (Ministerio de Comercio Exterior y Turismo) classification, Municipal Licencia de Funcionamiento",
      typicalTimeline: "2-4 months",
      renewalFrequency: "Municipal license varies; MINCETUR classification reviewed every 5 years",
      estimatedCost: "$300-$2,000",
      notes: "DS 001-2015-MINCETUR governs hotel classification (1-5 stars). DIRCETUR (regional tourism directorate) handles registration. Defensa Civil (civil defense) safety certification mandatory before operation.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-6 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "Municipal urban development plans govern zoning. SENACE (Servicio Nacional de Certificación Ambiental) handles environmental assessment for large projects. Ministerio de Cultura review required near archaeological sites (extremely common in Peru). Cusco historic center has strict UNESCO heritage controls.",
    },
    buildingCodes: {
      fireCodeStandard: "Reglamento Nacional de Edificaciones (RNE) — Norma A.130 (fire safety); INDECI (civil defense) inspection",
      adaEquivalent: "Ley 29973 (Ley General de la Persona con Discapacidad); RNE Norma A.120 (accessibility)",
      seismicRequirements: true,
      energyEfficiencyCode: "No mandatory energy efficiency code; voluntary LEED/EDGE certification gaining traction",
      maxOccupancyRegulation: "INDECI (civil defense) determines occupancy through ITSE (Technical Safety Inspection)",
      notes: "Peru is in a very high seismic zone — RNE Norma E.030 (Diseño Sismorresistente) is strictly enforced. Lima, coastal areas, and Cusco are particularly vulnerable. ITSE (Inspección Técnica de Seguridad en Edificaciones) mandatory before obtaining operating license.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No restrictions on foreign ownership of urban property. Within 50km of borders, foreigners cannot directly own property (constitutional restriction) — but may hold through a Peruvian company.",
      repatriationRestrictions: false,
      treatyProtections: "US-Peru TPA (Trade Promotion Agreement, 2009); numerous BITs",
      notes: "Peru has an open investment regime. Foreign investment registered with ProInversión. Tax stability agreements available for large investments (>$10M). Alcabala (property transfer tax) 3% of sale price. Peru's free trade agreement with the US provides strong investment protections.",
    },
    labor: {
      minimumWage: "PEN 1,130/month (2025 — adjusted periodically)",
      mandatoryBenefits: "EsSalud (health — employer 9%), CTS (Compensación por Tiempo de Servicios — ~1 month/year deposited biannually), gratificaciones (2 extra salary payments July + December), vacation (30 days), profit sharing (8% of pre-tax profits for hospitality sector)",
      terminationRules: "Just cause required for termination of indefinite contracts. Arbitrary dismissal: indemnización of 1.5 months' salary per year (capped at 12 months). Fixed-term contracts widely used but regulated.",
      unionPrevalence: "Low to moderate in hospitality.",
      notes: "Profit sharing (participación de utilidades) at 8% for hospitality sector is mandatory and a significant cost. CTS accrual adds approximately 1 month's salary per year. Total employer burden approximately 40-50% above base salary. Small enterprise regime (microempresa/pequeña empresa) offers reduced labor benefits for qualifying businesses.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "DS 001-2015-MINCETUR (Hotel Classification)",
      "Reglamento Nacional de Edificaciones (RNE)",
      "Ley General de la Persona con Discapacidad 29973",
      "US-Peru TPA text",
    ],
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Country code mapping (country name → ISO 2-letter code)
// ─────────────────────────────────────────────────────────────────────────────
