/**
 * check-schema-drift.ts
 *
 * Detects schema drift: runs `drizzle-kit generate` against a temp output
 * directory and fails if any new SQL is produced.
 *
 * Rationale: The Drizzle snapshot (lib/db/migrations/meta/0042_snapshot.json)
 * encodes the "last known state" of the database schema. If a developer adds
 * or alters a column in a schema file without running `drizzle-kit generate`
 * to produce a migration, the snapshot falls out of sync. This check catches
 * that drift before it reaches production.
 *
 * Implementation notes:
 * - A temporary output directory is created so the real migrations folder is
 *   never touched.
 * - The meta/ snapshot folder is copied to the temp dir so drizzle-kit can
 *   read the current baseline and compute the diff.
 * - A lightweight .mjs config (no requireDbUrl()) is written to the temp dir;
 *   drizzle-kit generate does NOT connect to the database, so a dummy URL is
 *   safe.
 * - The temp dir and all its contents are always deleted on exit.
 *
 * Exits 0 when the schema is in sync with the snapshot.
 * Exits 1 when drift is detected or an unexpected error occurs.
 *
 * Run via:
 *   pnpm --filter @workspace/scripts run check:schema-drift
 */

import { execSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  computeInputsHash,
  tryCacheHit,
  walkFilesForCache,
  WORKSPACE_ROOT,
  writeCacheHit,
} from "./lib/check-cache.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DB_LIB = path.join(WORKSPACE_ROOT, "lib/db");
const SCHEMA_ENTRY = path.join(DB_LIB, "src/schema/index.ts");
const MIGRATIONS_META_SRC = path.join(DB_LIB, "migrations/meta");

// ── Cache key ───────────────────────────────────────────────────────────────

export function collectInputFiles(): string[] {
  const files: string[] = [fileURLToPath(import.meta.url)];
  for (const f of walkFilesForCache(path.join(DB_LIB, "src"), {
    extensions: new Set([".ts"]),
    skipDirs: new Set(["node_modules"]),
  })) {
    files.push(f);
  }
  for (const f of walkFilesForCache(path.join(DB_LIB, "migrations"), {
    extensions: new Set([".sql", ".json"]),
    skipDirs: new Set(["node_modules"]),
  })) {
    files.push(f);
  }
  return files;
}

// ── Helpers ────────────────────────────────────────────────────────────────

function fail(reason: string): never {
  console.error(`\n✖  check:schema-drift — ${reason}\n`);
  process.exit(1);
}

// ── Main ───────────────────────────────────────────────────────────────────

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const inputHash = computeInputsHash({ files: collectInputFiles() });
  if (tryCacheHit("schema-drift", inputHash)) process.exit(0);

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "hplus-schema-drift-"));

  function cleanup() {
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    } catch {
      // best-effort
    }
  }

  // Register cleanup on all exit paths.
  process.on("exit", cleanup);
  process.on("SIGINT", () => process.exit(130));
  process.on("SIGTERM", () => process.exit(143));

  if (!fs.existsSync(SCHEMA_ENTRY)) {
    fail(`schema entry not found: ${SCHEMA_ENTRY}`);
  }

  if (!fs.existsSync(MIGRATIONS_META_SRC)) {
    fail(`migrations/meta not found: ${MIGRATIONS_META_SRC}`);
  }

  // 1. Copy migrations/meta into the temp output dir so drizzle-kit can read the
  //    current snapshot baseline.
  const tmpMeta = path.join(tmpDir, "meta");
  fs.mkdirSync(tmpMeta, { recursive: true });

  for (const file of fs.readdirSync(MIGRATIONS_META_SRC)) {
    fs.copyFileSync(
      path.join(MIGRATIONS_META_SRC, file),
      path.join(tmpMeta, file),
    );
  }

  // 2. Write a minimal ESM config that points at the real schema and uses the
  //    temp dir as the output. A dummy database URL is used because
  //    drizzle-kit generate never connects to Postgres — it only reads the
  //    snapshot and inspects the TypeScript schema.
  const tmpConfig = path.join(tmpDir, "drizzle.drift-check.config.mjs");
  fs.writeFileSync(
    tmpConfig,
    [
      `// Auto-generated by check-schema-drift — do not commit`,
      `import { defineConfig } from "drizzle-kit";`,
      `export default defineConfig({`,
      `  schema: ${JSON.stringify(SCHEMA_ENTRY)},`,
      `  out: ${JSON.stringify(tmpDir)},`,
      `  dialect: "postgresql",`,
      `  dbCredentials: { url: "postgresql://drift:check@localhost:5432/drift_check" },`,
      `});`,
    ].join("\n") + "\n",
  );

  // 3. Run drizzle-kit generate. Use the drizzle-kit binary from lib/db's
  //    node_modules so the version always matches the project's pinned version.
  const drizzleKitBin = path.join(DB_LIB, "node_modules/.bin/drizzle-kit");

  if (!fs.existsSync(drizzleKitBin)) {
    fail(
      `drizzle-kit binary not found at ${drizzleKitBin}.\n` +
        "  Run: pnpm install",
    );
  }

  try {
    execSync(`"${drizzleKitBin}" generate --config "${tmpConfig}"`, {
      cwd: DB_LIB,
      stdio: "pipe",
      env: {
        ...process.env,
        // Unset POSTGRES_URL / DATABASE_URL so if any module reads them it gets
        // the dummy value from the config, not the real production credentials.
        POSTGRES_URL: "",
        DATABASE_URL: "",
      },
    });
  } catch (err: unknown) {
    const e = err as { stdout?: Buffer; stderr?: Buffer; message?: string };
    const stderr = e.stderr?.toString().trim() ?? "";
    const stdout = e.stdout?.toString().trim() ?? "";
    fail(
      `drizzle-kit generate exited with an error.\n` +
        (stdout ? `  stdout: ${stdout}\n` : "") +
        (stderr ? `  stderr: ${stderr}\n` : "") +
        `  This may indicate a syntax error in the schema files or a missing\n` +
        `  dependency. Fix the schema error and re-run this check.`,
    );
  }

  // 4. Check whether any new .sql files were generated.
  const generatedSql = fs
    .readdirSync(tmpDir)
    .filter((f) => f.endsWith(".sql"));

  if (generatedSql.length === 0) {
    writeCacheHit("schema-drift", inputHash);
    console.log(
      `✓  check:schema-drift: schema matches snapshot — no drift detected.`,
    );
    process.exit(0);
  }

  // 5. Drift detected — print the SQL diff and fail.
  console.error(
    `\n✖  check:schema-drift — ${generatedSql.length} new migration(s) would be generated:\n`,
  );

  for (const sqlFile of generatedSql) {
    const contents = fs.readFileSync(path.join(tmpDir, sqlFile), "utf-8").trim();
    console.error(`  ── ${sqlFile} ──────────────────────────────────`);
    for (const line of contents.split("\n")) {
      console.error(`  ${line}`);
    }
    console.error("");
  }

  console.error(
    `  To fix, run the following from the workspace root and commit the result:\n` +
      `\n` +
      `    pnpm --filter @workspace/db run generate\n` +
      `\n` +
      `  Then add the generated .sql file and updated snapshot to your commit.\n`,
  );

  process.exit(1);
}
