import type { RegulatoryProfile } from "../regulatory-data";

export const REGULATORY_PROFILES_EUROPE: Record<string, RegulatoryProfile> = {
  "GB": {
    country: "United Kingdom",
    countryCode: "GB",
    licensing: {
      nationalLicenseRequired: false,
      localPermitRequired: true,
      licenseType: "Planning Permission (Change of Use), Premises Licence (Licensing Act 2003), Food Hygiene Registration",
      typicalTimeline: "3-6 months for planning; 2-3 months for premises licence",
      renewalFrequency: "Premises licence does not expire (one-time grant with annual fee). Planning permission is permanent unless conditional.",
      estimatedCost: "£2,000-£10,000+ (planning application fees vary by property size; premises licence £100-£1,905 based on rateable value)",
      notes: "England, Scotland, Wales, and Northern Ireland have separate planning regimes. Premises Licence under Licensing Act 2003 required for alcohol sales, entertainment, late-night refreshments. Separate Food Business Registration with local Environmental Health.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-8 months (8-13 weeks statutory determination period for planning; can extend significantly)",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "Change of Use from residential (Use Class C3) to hotel (Use Class C1) requires full planning permission. Permitted development rights do NOT cover C3→C1. Listed building consent required for Grade I/II* properties — Heritage England must be consulted. Conservation Area restrictions apply broadly in desirable locations. England uses the NPPF (National Planning Policy Framework).",
    },
    buildingCodes: {
      fireCodeStandard: "Building Regulations Part B (Fire Safety); Regulatory Reform (Fire Safety) Order 2005; post-Grenfell Fire Safety Act 2021",
      adaEquivalent: "Equality Act 2010 + Building Regulations Part M (Access to and use of buildings)",
      seismicRequirements: false,
      energyEfficiencyCode: "Building Regulations Part L (Conservation of fuel and power); EPC (Energy Performance Certificate) required — minimum E rating for commercial lettings",
      maxOccupancyRegulation: "Fire Risk Assessment determines maximum occupancy; Housing Act standards for sleeping accommodation",
      notes: "Post-Grenfell reforms have significantly tightened fire safety requirements. Buildings over 18m have additional requirements. EPC minimum standards are expected to tighten to C by 2027-2028 — factor retrofit costs into projections.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No restrictions on foreign ownership of real property. National Security and Investment Act 2021 allows government review of acquisitions in sensitive sectors (hospitality is generally not sensitive).",
      repatriationRestrictions: false,
      treatyProtections: "Numerous BITs; UK-US tax treaty for double taxation relief",
      notes: "UK is one of the most open markets for foreign real estate investment. Non-resident capital gains tax applies to UK property dispositions (since 2019). Stamp Duty Land Tax (SDLT) applies to purchases — 2% surcharge for non-UK residents. Annual Tax on Enveloped Dwellings (ATED) may apply if held through a company.",
    },
    labor: {
      minimumWage: "£12.21/hr (National Living Wage, age 21+, April 2025 rate)",
      mandatoryBenefits: "Employer NIC (~13.8%), auto-enrollment pension (employer min 3%), statutory sick pay, 28 days paid holiday (incl. bank holidays), statutory maternity/paternity pay",
      terminationRules: "Unfair dismissal protection after 2 years' continuous service. Statutory notice periods (1 week per year of service, up to 12 weeks). Redundancy consultation requirements.",
      unionPrevalence: "Low in hospitality. Unite and GMB have some hotel sector membership.",
      notes: "Employer National Insurance is a significant payroll cost. Tips/gratuities must be passed to workers in full under the Employment (Allocation of Tips) Act 2023. Skilled Worker visa route available for hospitality managers (but not front-line roles as of 2025 — check current SOL list).",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "https://www.gov.uk/planning-permission-england-wales",
      "https://www.legislation.gov.uk/ukpga/2003/17/contents (Licensing Act 2003)",
      "https://www.gov.uk/national-minimum-wage-rates",
      "Building Regulations 2010 (England & Wales)",
      "National Planning Policy Framework (NPPF)",
    ],
  },

  "FR": {
    country: "France",
    countryCode: "FR",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "Déclaration en mairie (mandatory registration with mayor's office), Atout France classification (star rating), Licence IV (liquor)",
      typicalTimeline: "2-4 months for registration; classification visit can take additional 2-3 months",
      renewalFrequency: "Classification valid for 5 years; business registration ongoing",
      estimatedCost: "EUR 1,000-5,000 (classification fees + municipal charges)",
      notes: "All accommodation establishments must register with the local mairie (town hall) via CERFA form. Atout France star classification is voluntary but nearly universal and affects tax treatment (taxe de séjour rates). Licence IV for alcohol is transferable but increasingly scarce and expensive in major cities.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-8 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "PLU (Plan Local d'Urbanisme) governs zoning. Change of destination (changement de destination) from residential to hotel requires planning permission (permis de construire or déclaration préalable). ABF (Architecte des Bâtiments de France) approval mandatory in conservation areas — near a Monument Historique or in a Site Patrimonial Remarquable. Can significantly extend timeline.",
    },
    buildingCodes: {
      fireCodeStandard: "Réglementation ERP (Établissements Recevant du Public) — Type O for hotels; Commission de Sécurité approval required",
      adaEquivalent: "Loi handicap 2005 (Loi n° 2005-102); Ad'AP (Agenda d'Accessibilité Programmée)",
      seismicRequirements: false,
      energyEfficiencyCode: "RT 2020 / RE 2020 (Réglementation Environnementale) for new construction; DPE (Diagnostic de Performance Énergétique) for existing",
      maxOccupancyRegulation: "Commission de Sécurité (ERP regulations) determines capacity based on building classification",
      notes: "ERP regulations are strict — fire safety commission must approve before opening. Hotels are Type O ERP. Category depends on capacity (5th category: <100 persons). Lead and asbestos diagnostics (DTA, CREP) mandatory for pre-1997 buildings.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No general restrictions for EU nationals. Non-EU investors require no special authorization for most real estate. Ministry of Economy can review acquisitions in 'strategic sectors' (hospitality is generally not covered).",
      repatriationRestrictions: false,
      treatyProtections: "EU single market protections; French BITs with 100+ countries; US-France tax treaty",
      notes: "France imposes a 3% tax on real property held by foreign entities (taxe de 3%) unless tax treaty exemption applies. Wealth tax (IFI) may apply to real estate holdings above EUR 1.3M. Notaire fees on purchase approximately 7-8% of purchase price.",
    },
    labor: {
      minimumWage: "EUR 11.88/hr (SMIC brut, 2025 — typically revised annually)",
      mandatoryBenefits: "Employer social charges ~42-45% of gross salary (sécurité sociale, retraite, chômage, formation), 5 weeks paid vacation, RTT (reduced working time) days, 13th month (common by convention collective HCR)",
      terminationRules: "Strict just cause (cause réelle et sérieuse) required. CDI (permanent contracts) dominate. Dismissal process is heavily regulated with mandatory interviews, notice periods, and severance (indemnité de licenciement). Prud'hommes (labor court) strongly favors employees.",
      unionPrevalence: "Moderate. Convention Collective Nationale des HCR (Hotels, Cafés, Restaurants) governs the sector. Multiple unions active (CFDT, CGT, FO).",
      notes: "France's employer social charges are among the highest globally — total employer cost is approximately 1.4-1.5x base salary. 35-hour workweek. Overtime regulated. CDD (fixed-term) contracts limited to specific circumstances. Convention Collective HCR sets minimum wages above SMIC for most hospitality roles.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "https://www.legifrance.gouv.fr/",
      "Réglementation ERP (Arrêté du 25 juin 1980)",
      "Convention Collective Nationale des HCR",
      "https://www.atout-france.fr/",
      "Code de l'urbanisme",
    ],
  },

  "ES": {
    country: "Spain",
    countryCode: "ES",
    licensing: {
      nationalLicenseRequired: false,
      localPermitRequired: true,
      licenseType: "Licencia de Apertura (municipal opening license), Registro de Turismo (autonomous community tourism registry), Licencia de Actividad",
      typicalTimeline: "2-6 months (varies significantly by autonomous community)",
      renewalFrequency: "Tourism registration is ongoing; activity license does not typically expire",
      estimatedCost: "EUR 1,000-5,000",
      notes: "Tourism regulation is devolved to the 17 Comunidades Autónomas — each has its own tourism law and classification system. Andalucía, Cataluña, and Baleares have particularly detailed hotel regulations. Declaración responsable (responsible declaration) has replaced some licensing in certain regions, speeding up the process.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-8 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "PGOU (Plan General de Ordenación Urbana) governs municipal zoning. Change of use requires licencia urbanística. Many urban centers have tourist saturation restrictions (Barcelona, Palma de Mallorca limit new hotel licenses). BIC (Bien de Interés Cultural) designation imposes strict heritage controls.",
    },
    buildingCodes: {
      fireCodeStandard: "CTE (Código Técnico de la Edificación) — Documento Básico SI (Seguridad en caso de Incendio)",
      adaEquivalent: "CTE Documento Básico SUA (Seguridad de Utilización y Accesibilidad); autonomous community accessibility laws",
      seismicRequirements: true,
      energyEfficiencyCode: "CTE Documento Básico HE (Ahorro de Energía); mandatory EPC (Certificado de Eficiencia Energética)",
      maxOccupancyRegulation: "CTE occupancy calculations + autonomous community tourism regulations (minimum room sizes, etc.)",
      notes: "CTE is comprehensive and mandatory for all new construction and major renovations. Seismic requirements primarily apply to southern Spain (Andalucía, Murcia — NCSE-02). Minimum room sizes for hotels set by each autonomous community's tourism law.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No restrictions for EU/EEA nationals. Non-EU investors must obtain NIE (Número de Identidad de Extranjero). No ownership limits on real property.",
      repatriationRestrictions: false,
      treatyProtections: "EU single market; Spain has BITs with 70+ countries; US-Spain tax treaty",
      notes: "Golden Visa program: EUR 500,000+ real estate investment grants residency permit. ITP (Impuesto sobre Transmisiones Patrimoniales) on resale purchases typically 6-10% depending on autonomous community. New construction subject to IVA (21%).",
    },
    labor: {
      minimumWage: "EUR 1,134/month (14 payments/year, SMI 2025)",
      mandatoryBenefits: "Employer social security ~30% of gross salary, 30 days paid vacation, 14 salary payments/year (paga extra), sick leave coverage",
      terminationRules: "Dismissal requires objective or disciplinary cause. Improcedente (unfair) dismissal: 33 days' salary per year of service (max 24 months). ERE (collective dismissal) requires government approval.",
      unionPrevalence: "Moderate. Convenio Colectivo de Hostelería applies by province. CCOO and UGT are major unions.",
      notes: "Labor costs structured around 14 annual payments (12 monthly + 2 extra pays). Provincial hospitality agreements (Convenio Colectivo de Hostelería) set wages above SMI for most roles. Temporary contracts heavily regulated since 2022 labor reform.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "Código Técnico de la Edificación (CTE)",
      "Autonomous community tourism laws",
      "https://www.boe.es/",
      "Ley de Propiedad Horizontal",
    ],
  },

  "IT": {
    country: "Italy",
    countryCode: "IT",
    licensing: {
      nationalLicenseRequired: false,
      localPermitRequired: true,
      licenseType: "SCIA (Segnalazione Certificata di Inizio Attività) filed with municipality, Regional Tourism Classification, ASL (health authority) authorization",
      typicalTimeline: "2-4 months",
      renewalFrequency: "SCIA is ongoing; classification renewed periodically per regional law",
      estimatedCost: "EUR 500-3,000",
      notes: "Tourism regulation is regional (20 regions, each with own classification system). SCIA has streamlined business opening — allows operation after filing if requirements are met. ASL (Azienda Sanitaria Locale) health inspection mandatory for F&B. Star classification administered by each region.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-8 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "PRG/PGT (Piano Regolatore Generale / Piano di Governo del Territorio) governs municipal zoning. Cambio di destinazione d'uso requires permesso di costruire or SCIA depending on scope. Soprintendenza (heritage authority) approval required for properties in historic centers — extremely common in Italian cities. Vincolo paesaggistico (landscape constraints) widespread.",
    },
    buildingCodes: {
      fireCodeStandard: "DM 9 aprile 1994 (hotel fire safety regulation) + DM 3 agosto 2015 (new fire prevention code)",
      adaEquivalent: "DM 236/1989 (accessibility requirements); DPR 503/1996 (public buildings accessibility)",
      seismicRequirements: true,
      energyEfficiencyCode: "DLgs 192/2005 (energy performance of buildings, implementing EU EPBD); APE (Attestato di Prestazione Energetica) mandatory",
      maxOccupancyRegulation: "Vigili del Fuoco (fire brigade) determine capacity; SCIA antincendio required for hotels",
      notes: "Italy is seismically active — NTC 2018 (Norme Tecniche per le Costruzioni) is the current structural code. Central Italy (L'Aquila, Norcia) and southern regions are highest risk. Soprintendenza reviews can add months to projects in historic areas. Certificato di Agibilità required before opening.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No restrictions for EU nationals. Non-EU investors subject to reciprocity principle (most major countries qualify). No ownership limits.",
      repatriationRestrictions: false,
      treatyProtections: "EU single market; Italy BITs with 90+ countries; US-Italy tax treaty",
      notes: "Imposta di registro (registration tax) on resale: 9% (reduced to 2% for first home — not applicable to hotels). IVA (22%) on new construction. Notaio fees approximately 1-2.5%. Flat tax regime for new residents may benefit individual investors.",
    },
    labor: {
      minimumWage: "No statutory national minimum wage — wages set by CCNL (Contratti Collettivi Nazionali di Lavoro). CCNL Turismo sets hospitality minimums (~EUR 1,300-1,700/month depending on level).",
      mandatoryBenefits: "Employer social contributions ~30-32% of gross; TFR (Trattamento di Fine Rapporto — severance accrual ~6.9%/year); 13th and 14th month salary; 26 days vacation",
      terminationRules: "Just cause or justified reason required. Individual dismissal: notice period per CCNL + TFR payout. Collective dismissal (5+ workers in 120 days): complex procedure with unions and labor office.",
      unionPrevalence: "Moderate to high. CCNL Turismo negotiated by FILCAMS-CGIL, FISASCAT-CISL, UILTuCS-UIL. Sector-wide bargaining sets terms for all workers.",
      notes: "CCNL Turismo governs virtually all hospitality employment terms. 14 monthly payments standard. TFR accrual is a significant ongoing cost. Total employer burden approximately 40-45% above gross salary.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "NTC 2018 (Norme Tecniche per le Costruzioni)",
      "CCNL Turismo",
      "DM 9 aprile 1994 (fire safety for hotels)",
      "https://www.agenziaentrate.gov.it/",
    ],
  },

  "PT": {
    country: "Portugal",
    countryCode: "PT",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "Turismo de Portugal registration (AL — Alojamento Local, or hotel classification), Câmara Municipal (municipal) license",
      typicalTimeline: "2-4 months",
      renewalFrequency: "AL registration ongoing; hotel classification reviewed periodically",
      estimatedCost: "EUR 500-3,000",
      notes: "AL (Alojamento Local) regime has been significantly restricted in many municipalities since 2023 ('Mais Habitação' law). New AL licenses suspended in many Lisbon and Porto parishes. Hotel classification (1-5 stars) through Turismo de Portugal is a separate regime with different requirements.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-8 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "PDM (Plano Director Municipal) governs zoning. Many historic city centers are UNESCO-protected or nationally classified — Câmara Municipal and DGPC (heritage authority) approval required. Coastal zone (POOC) has development restrictions.",
    },
    buildingCodes: {
      fireCodeStandard: "SCIE (Segurança Contra Incêndios em Edifícios) — DL 220/2008 + Portaria 1532/2008",
      adaEquivalent: "DL 163/2006 (accessibility regime for public buildings)",
      seismicRequirements: true,
      energyEfficiencyCode: "REH/RECS (building energy regulation); mandatory EPC (Certificado Energético)",
      maxOccupancyRegulation: "SCIE fire safety assessment determines occupancy",
      notes: "Portugal is seismically active (particularly Lisbon, Algarve). Eurocode 8 seismic provisions apply. Pre-1755 and pre-1958 buildings may require significant structural assessment.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No restrictions. Golden Visa program ended for real estate in 2023 but existing visas honored.",
      repatriationRestrictions: false,
      treatyProtections: "EU single market; Portuguese BITs; US-Portugal tax treaty",
      notes: "IMT (property transfer tax) 1-7.5% depending on value. NHR (Non-Habitual Resident) tax regime reformed in 2024 — replaced by IFICI for qualifying professionals. Stamp duty 0.8%.",
    },
    labor: {
      minimumWage: "EUR 870/month (14 payments; 2025)",
      mandatoryBenefits: "Employer social security ~23.75%; 14 salary payments; 22 days vacation; sick leave coverage",
      terminationRules: "Just cause required. Collective dismissal heavily regulated. Indemnización for dismissal. Labor courts favor workers.",
      unionPrevalence: "Low to moderate in hospitality.",
      notes: "Total employer burden approximately 30-35% above gross salary. 14 monthly payments standard.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "https://www.turismodeportugal.pt/",
      "DL 220/2008 (SCIE)",
      "Código do Trabalho (Portugal)",
    ],
  },

  "GR": {
    country: "Greece",
    countryCode: "GR",
    licensing: {
      nationalLicenseRequired: true,
      localPermitRequired: true,
      licenseType: "EOT (Greek National Tourism Organisation) Special Operating License, Municipal permit",
      typicalTimeline: "3-6 months",
      renewalFrequency: "EOT license valid for 5 years (renewable)",
      estimatedCost: "EUR 1,000-5,000",
      notes: "EOT (now under Ministry of Tourism) classifies all hotels. Technical specifications (room sizes, amenities) depend on star classification. Environmental and fire safety approvals are prerequisites.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "4-12 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "Greek planning is complex. Building permit (Oikodomiki Adeia) required. Archaeological survey mandatory in many areas — Ministry of Culture review can significantly delay projects. Coastal zone (50m from shoreline) generally prohibited from development. Island construction often subject to additional Cycladic/local architectural requirements.",
    },
    buildingCodes: {
      fireCodeStandard: "Fire Protection Regulations (PD 71/1988, updated); fire department (Pyrosvestiki) certification",
      adaEquivalent: "Accessibility provisions in Building Code (NOK); Law 4067/2012 (New Building Code)",
      seismicRequirements: true,
      energyEfficiencyCode: "KENAK (Regulation on Energy Performance of Buildings) implementing EU EPBD; mandatory EPC",
      maxOccupancyRegulation: "Fire department and EOT technical specifications",
      notes: "Greece is in a high seismic zone — EAK 2000 (Greek Seismic Code) and Eurocode 8 apply. Anti-seismic design is critical throughout the country.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "Restrictions on property acquisition near national borders (requires approval from a local committee). No restrictions for EU nationals in most areas.",
      repatriationRestrictions: false,
      treatyProtections: "EU single market; Greek BITs; US-Greece tax treaty",
      notes: "Golden Visa: EUR 250,000+ investment (increased to EUR 500,000 in certain areas). Property transfer tax 3.09%. Strategic Investment Law (4608/2019) provides incentives for large tourism projects.",
    },
    labor: {
      minimumWage: "EUR 830/month (14 payments; 2025 — subject to annual review)",
      mandatoryBenefits: "Employer social security ~22.29% (EFKA); 14 salary payments; 20-26 days vacation; sick leave",
      terminationRules: "Notice period required (varies by tenure — up to 4 months). Severance for employees with 12+ months tenure. Mass dismissal restrictions.",
      unionPrevalence: "Moderate. National General Collective Labor Agreement (EGSSE) sets baseline terms. Hotel sector agreements exist.",
      notes: "14 salary payments standard (extra at Easter, summer, Christmas). Seasonal employment contracts common in island tourism. Total employer burden approximately 30% above gross.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "https://www.mintour.gov.gr/",
      "EAK 2000 (Greek Seismic Code)",
      "KENAK (Energy Performance Regulation)",
    ],
  },
};
