import {
  PropertyStatus,
  DEFAULT_COST_RATE_ROOMS,
  DEFAULT_COST_RATE_FB,
  DEFAULT_COST_RATE_ADMIN,
  DEFAULT_COST_RATE_MARKETING,
  DEFAULT_COST_RATE_PROPERTY_OPS,
  DEFAULT_COST_RATE_UTILITIES,
  DEFAULT_COST_RATE_TAXES,
  DEFAULT_COST_RATE_IT,
  DEFAULT_COST_RATE_FFE,
  DEFAULT_COST_RATE_OTHER,
  DEFAULT_COST_RATE_INSURANCE,
  DEFAULT_REV_SHARE_EVENTS,
  DEFAULT_REV_SHARE_FB,
  DEFAULT_REV_SHARE_OTHER,
  DEFAULT_EXIT_CAP_RATE,
  DEFAULT_PROPERTY_TAX_RATE,
  DEFAULT_COMMISSION_RATE,
  DEFAULT_BASE_MANAGEMENT_FEE_RATE,
  DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
  DEFAULT_LAND_VALUE_PERCENT,
} from "@shared/constants";

export const SEED_PROPERTY_DEFAULTS = {
  costRateRooms: DEFAULT_COST_RATE_ROOMS, costRateFB: DEFAULT_COST_RATE_FB, costRateAdmin: DEFAULT_COST_RATE_ADMIN,
  costRateMarketing: DEFAULT_COST_RATE_MARKETING, costRatePropertyOps: DEFAULT_COST_RATE_PROPERTY_OPS,
  costRateUtilities: DEFAULT_COST_RATE_UTILITIES,
  costRateTaxes: DEFAULT_COST_RATE_TAXES, costRateIT: DEFAULT_COST_RATE_IT, costRateFFE: DEFAULT_COST_RATE_FFE,
  costRateOther: DEFAULT_COST_RATE_OTHER, costRateInsurance: DEFAULT_COST_RATE_INSURANCE,
  revShareEvents: DEFAULT_REV_SHARE_EVENTS,
  revShareFB: DEFAULT_REV_SHARE_FB, revShareOther: DEFAULT_REV_SHARE_OTHER,
  exitCapRate: DEFAULT_EXIT_CAP_RATE, taxRate: DEFAULT_PROPERTY_TAX_RATE,
  dispositionCommission: DEFAULT_COMMISSION_RATE,
  baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
  incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
};

export const SEED_INITIAL_PROPERTIES = [
  {
    userId: null,
    name: "Jano Grande Ranch",
    description: "A luxury hacienda retreat set in the lush hills of Antioquia, offering curated cultural experiences and farm-to-table dining amid Colombia's coffee country.",
    streetAddress: "Vereda El Salado",
    city: "Medellín",
    stateProvince: "Antioquia",
    zipPostalCode: "050001",
    country: "Colombia",
    location: "Antioquia, Medellín",
    market: "Latin America",
    imageUrl: "/images/property-medellin.png",
    status: PropertyStatus.PLANNED,
    acquisitionDate: "2026-06-01",
    operationsStartDate: "2026-12-01",
    purchasePrice: 1200000,
    buildingImprovements: 400000,
    preOpeningCosts: 150000,
    operatingReserve: 300000,
    roomCount: 20,
    startAdr: 250,
    adrGrowthRate: 0.035,
    startOccupancy: 0.40,
    maxOccupancy: 0.72,
    occupancyRampMonths: 9,
    stabilizationMonths: 36,
    occupancyGrowthStep: 0.05,
    type: "Full Equity",
    willRefinance: "Yes",
    refinanceDate: "2029-12-01",
    refinanceLTV: 0.75,
    refinanceInterestRate: 0.09,
    refinanceTermYears: 25,
    refinanceClosingCostRate: 0.03,
    refinanceYearsAfterAcquisition: 3,
    dispositionCommission: DEFAULT_COMMISSION_RATE,
    costRateRooms: 0.17,
    costRateFB: 0.10,
    costRateAdmin: 0.06,
    costRateMarketing: 0.015,
    costRatePropertyOps: 0.05,
    costRateUtilities: 0.04,
    costRateTaxes: 0.016,
    costRateIT: 0.005,
    costRateFFE: 0.04,
    costRateOther: 0.05,
    revShareEvents: 0.30,
    revShareFB: 0.25,
    revShareOther: 0.08,
    cateringBoostPercent: 0.25,
    exitCapRate: 0.10,
    taxRate: 0.09,
    baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
    incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
  },
  {
    userId: null,
    name: "Loch Sheldrake",
    description: "A 10-acre lakeside estate featuring an iconic octagonal main house, three private bodies of water, a private island with gazebo, and income-generating apartment. Set in Sullivan County's Catskill region with event venue potential for weddings, retreats, and luxury Airbnb experiences.",
    streetAddress: "59 Hazelnis Drive",
    city: "Loch Sheldrake",
    stateProvince: "New York",
    zipPostalCode: "12759",
    country: "United States",
    location: "Sullivan County, New York",
    market: "North America",
    imageUrl: "/images/property-loch-sheldrake.png",
    status: PropertyStatus.PLANNED,
    acquisitionDate: "2026-11-01",
    operationsStartDate: "2027-05-01",
    purchasePrice: 3000000,
    buildingImprovements: 1000000,
    preOpeningCosts: 150000,
    operatingReserve: 400000,
    roomCount: 20,
    startAdr: 280,
    adrGrowthRate: 0.035,
    startOccupancy: 0.50,
    maxOccupancy: 0.68,
    occupancyRampMonths: 4,
    stabilizationMonths: 18,
    occupancyGrowthStep: 0.05,
    type: "Full Equity",
    willRefinance: "Yes",
    refinanceDate: "2030-05-01",
    refinanceLTV: 0.75,
    refinanceInterestRate: 0.09,
    refinanceTermYears: 25,
    refinanceClosingCostRate: 0.03,
    refinanceYearsAfterAcquisition: 3,
    dispositionCommission: DEFAULT_COMMISSION_RATE,
    costRateRooms: 0.19,
    costRateFB: 0.09,
    costRateAdmin: 0.07,
    costRateMarketing: 0.02,
    costRatePropertyOps: 0.055,
    costRateUtilities: 0.055,
    costRateTaxes: 0.035,
    costRateIT: 0.005,
    costRateFFE: 0.04,
    costRateOther: 0.04,
    revShareEvents: 0.35,
    revShareFB: 0.25,
    revShareOther: 0.08,
    cateringBoostPercent: 0.22,
    exitCapRate: 0.09,
    taxRate: 0.25,
    baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
    incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
  },
  {
    userId: null,
    name: "Belleayre Mountain",
    description: "An alpine lodge nestled in the Western Catskills, offering four-season mountain recreation with ski-in access and panoramic ridge-line views.",
    streetAddress: "Upper Delaware River Valley",
    city: "Highmount",
    stateProvince: "New York",
    zipPostalCode: "12441",
    country: "United States",
    location: "Western Catskills, New York",
    market: "North America",
    imageUrl: "/images/property-belleayre.png",
    status: PropertyStatus.PLANNED,
    acquisitionDate: "2027-03-01",
    operationsStartDate: "2027-09-01",
    purchasePrice: 3500000,
    buildingImprovements: 800000,
    preOpeningCosts: 250000,
    operatingReserve: 500000,
    roomCount: 20,
    startAdr: 320,
    adrGrowthRate: 0.035,
    startOccupancy: 0.40,
    maxOccupancy: 0.68,
    occupancyRampMonths: 12,
    stabilizationMonths: 36,
    occupancyGrowthStep: 0.05,
    type: "Full Equity",
    willRefinance: "Yes",
    refinanceDate: "2030-09-01",
    refinanceLTV: 0.75,
    refinanceInterestRate: 0.09,
    refinanceTermYears: 25,
    refinanceClosingCostRate: 0.03,
    refinanceYearsAfterAcquisition: 3,
    dispositionCommission: DEFAULT_COMMISSION_RATE,
    costRateRooms: 0.20,
    costRateFB: 0.09,
    costRateAdmin: 0.08,
    costRateMarketing: 0.02,
    costRatePropertyOps: 0.06,
    costRateUtilities: 0.055,
    costRateTaxes: 0.035,
    costRateIT: 0.005,
    costRateFFE: 0.04,
    costRateOther: 0.04,
    revShareEvents: 0.30,
    revShareFB: 0.28,
    revShareOther: 0.07,
    cateringBoostPercent: 0.20,
    exitCapRate: 0.085,
    taxRate: 0.25,
    baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
    incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
  },
  {
    userId: null,
    name: "Scott's House",
    description: "A modern mountain retreat in Utah's Ogden Valley, combining contemporary design with dramatic Wasatch Range views and year-round outdoor adventure.",
    streetAddress: "Eden",
    city: "Eden",
    stateProvince: "Utah",
    zipPostalCode: "84310",
    country: "United States",
    location: "Ogden Valley, Utah",
    market: "North America",
    imageUrl: "/images/property-eden.png",
    status: PropertyStatus.PLANNED,
    acquisitionDate: "2027-08-01",
    operationsStartDate: "2028-02-01",
    purchasePrice: 3200000,
    buildingImprovements: 800000,
    preOpeningCosts: 200000,
    operatingReserve: 400000,
    roomCount: 20,
    startAdr: 350,
    adrGrowthRate: 0.03,
    startOccupancy: 0.45,
    maxOccupancy: 0.65,
    occupancyRampMonths: 6,
    stabilizationMonths: 24,
    occupancyGrowthStep: 0.05,
    type: "Financed",
    acquisitionLTV: 0.60,
    acquisitionInterestRate: 0.07,
    acquisitionTermYears: 25,
    acquisitionClosingCostRate: 0.025,
    dispositionCommission: DEFAULT_COMMISSION_RATE,
    costRateRooms: 0.20,
    costRateFB: 0.08,
    costRateAdmin: 0.07,
    costRateMarketing: 0.02,
    costRatePropertyOps: 0.05,
    costRateUtilities: 0.05,
    costRateTaxes: 0.02,
    costRateIT: 0.005,
    costRateFFE: 0.04,
    costRateOther: 0.04,
    revShareEvents: 0.30,
    revShareFB: 0.20,
    revShareOther: 0.08,
    cateringBoostPercent: 0.20,
    exitCapRate: 0.085,
    taxRate: 0.22,
    baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
    incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
  },
  {
    userId: null,
    name: "Lakeview Haven Lodge",
    description: "Lakeview Haven Lodge is a unique cabin on the shores of Pineview Reservoir, nestled in the mountains of Ogden Valley, Utah. This spacious lodge sleeps up to 16 guests and features a great room with vaulted ceilings, a fully equipped gourmet kitchen, hot tub, sauna, pickleball court, gym, media room, and private lake access with kayaks and paddleboards. Perfect for family reunions, corporate retreats, and group getaways year-round.",
    streetAddress: "5597 Utah-39 Scenic",
    city: "Huntsville",
    stateProvince: "Utah",
    zipPostalCode: "84317",
    country: "United States",
    location: "Ogden Valley, Utah",
    market: "North America",
    imageUrl: "https://uc.orez.io/i/cd4aefa0f4fd4d76ba9b60dc003f8bfd-LargeOriginal",
    status: PropertyStatus.PLANNED,
    acquisitionDate: "2027-12-01",
    operationsStartDate: "2028-06-01",
    purchasePrice: 3800000,
    buildingImprovements: 1200000,
    preOpeningCosts: 250000,
    operatingReserve: 500000,
    roomCount: 8,
    businessModel: "lodge",
    hospitalityType: "lodge",
    startAdr: 320,
    adrGrowthRate: 0.03,
    startOccupancy: 0.50,
    maxOccupancy: 0.68,
    occupancyRampMonths: 3,
    stabilizationMonths: 18,
    occupancyGrowthStep: 0.05,
    type: "Financed",
    acquisitionLTV: 0.65,
    acquisitionInterestRate: 0.07,
    acquisitionTermYears: 25,
    acquisitionClosingCostRate: 0.025,
    dispositionCommission: DEFAULT_COMMISSION_RATE,
    costRateRooms: 0.20,
    costRateFB: 0.09,
    costRateAdmin: 0.07,
    costRateMarketing: 0.02,
    costRatePropertyOps: 0.055,
    costRateUtilities: 0.05,
    costRateTaxes: 0.02,
    costRateIT: 0.005,
    costRateFFE: 0.04,
    costRateOther: 0.04,
    revShareEvents: 0,
    revShareFB: 0.25,
    revShareOther: 0.05,
    cateringBoostPercent: 0,
    exitCapRate: 0.08,
    taxRate: 0.22,
    baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
    incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
  },
  {
    userId: null,
    name: "San Diego",
    description: "A colonial boutique hotel in Cartagena's historic walled city, blending 17th-century architecture with Caribbean luxury, rooftop dining, and old-world charm.",
    streetAddress: "Cochera del Hobo, Barrio San Diego",
    city: "Cartagena",
    stateProvince: "Bolívar",
    zipPostalCode: "130001",
    country: "Colombia",
    location: "Cartagena, Colombia",
    market: "Latin America",
    imageUrl: "/images/property-cartagena.png",
    status: PropertyStatus.PLANNED,
    acquisitionDate: "2028-04-01",
    operationsStartDate: "2028-10-01",
    purchasePrice: 2000000,
    buildingImprovements: 1000000,
    preOpeningCosts: 250000,
    operatingReserve: 500000,
    roomCount: 20,
    startAdr: 240,
    adrGrowthRate: 0.035,
    startOccupancy: 0.42,
    maxOccupancy: 0.72,
    occupancyRampMonths: 10,
    stabilizationMonths: 36,
    occupancyGrowthStep: 0.05,
    type: "Financed",
    acquisitionLTV: 0.60,
    acquisitionInterestRate: 0.095,
    acquisitionTermYears: 25,
    acquisitionClosingCostRate: 0.02,
    dispositionCommission: DEFAULT_COMMISSION_RATE,
    costRateRooms: 0.17,
    costRateFB: 0.09,
    costRateAdmin: 0.07,
    costRateMarketing: 0.015,
    costRatePropertyOps: 0.035,
    costRateUtilities: 0.04,
    costRateTaxes: 0.025,
    costRateIT: 0.005,
    costRateFFE: 0.04,
    costRateOther: 0.04,
    revShareEvents: 0.30,
    revShareFB: 0.24,
    revShareOther: 0.06,
    cateringBoostPercent: 0.20,
    exitCapRate: 0.09,
    taxRate: 0.35,
    baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
    incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
  },
];

export const SEED_SYNC_PROPERTIES = [
  { ...SEED_PROPERTY_DEFAULTS, name: "The Hudson Estate", streetAddress: "142 Old Post Road", city: "Millbrook", stateProvince: "NY", zipPostalCode: "12545", country: "United States", location: "Hudson Valley, New York", market: "North America", imageUrl: "/images/property-ny.png", status: PropertyStatus.PIPELINE, acquisitionDate: "2026-06-01", operationsStartDate: "2026-12-01", purchasePrice: 3800000, buildingImprovements: 1200000, preOpeningCosts: 200000, operatingReserve: 250000, roomCount: 20, startAdr: 385, adrGrowthRate: 0.025, startOccupancy: 0.55, maxOccupancy: 0.82, occupancyRampMonths: 6, occupancyGrowthStep: 0.05, type: "Full Equity", costRateFB: 0.085, costRateIT: 0.005, cateringBoostPercent: 0.22, exitCapRate: 0.08, willRefinance: "Yes", refinanceDate: "2029-12-01", refinanceLtv: 0.75, refinanceInterestRate: 0.09, refinanceTermYears: 25, refinanceClosingCostRate: 0.03, revShareEvents: 0.30 },
  { ...SEED_PROPERTY_DEFAULTS, name: "Eden Summit Lodge", streetAddress: "3850 Nordic Valley Road", city: "Eden", stateProvince: "UT", zipPostalCode: "84310", location: "Ogden Valley, Utah", market: "North America", imageUrl: "/images/property-utah.png", status: PropertyStatus.PIPELINE, acquisitionDate: "2027-01-01", operationsStartDate: "2027-07-01", purchasePrice: 4000000, buildingImprovements: 1200000, preOpeningCosts: 200000, operatingReserve: 250000, roomCount: 20, startAdr: 425, adrGrowthRate: 0.025, startOccupancy: 0.50, maxOccupancy: 0.80, occupancyRampMonths: 6, occupancyGrowthStep: 0.05, type: "Full Equity", costRateFB: 0.085, costRateIT: 0.005, cateringBoostPercent: 0.25, willRefinance: "Yes", refinanceDate: "2030-07-01", refinanceLtv: 0.75, refinanceInterestRate: 0.09, refinanceTermYears: 25, refinanceClosingCostRate: 0.03, revShareEvents: 0.30 },
  { ...SEED_PROPERTY_DEFAULTS, name: "Austin Hillside", streetAddress: "4100 Mount Bonnell Drive", city: "Austin", stateProvince: "TX", zipPostalCode: "78731", location: "Hill Country, Texas", market: "North America", imageUrl: "/images/property-austin.png", status: PropertyStatus.PIPELINE, acquisitionDate: "2027-04-01", operationsStartDate: "2028-01-01", purchasePrice: 3500000, buildingImprovements: 1100000, preOpeningCosts: 200000, operatingReserve: 250000, roomCount: 20, startAdr: 320, adrGrowthRate: 0.025, startOccupancy: 0.55, maxOccupancy: 0.82, occupancyRampMonths: 6, occupancyGrowthStep: 0.05, type: "Full Equity", costRateFB: 0.09, costRateIT: 0.005, cateringBoostPercent: 0.20, willRefinance: "Yes", refinanceDate: "2031-01-01", refinanceLtv: 0.75, refinanceInterestRate: 0.09, refinanceTermYears: 25, refinanceClosingCostRate: 0.03, revShareEvents: 0.28 },
  { ...SEED_PROPERTY_DEFAULTS, name: "Casa Medellín", streetAddress: "Carrera 43A #7-50, El Poblado", city: "Medellín", stateProvince: "Antioquia", zipPostalCode: "050021", country: "Colombia", location: "El Poblado, Medellín", market: "Latin America", imageUrl: "/images/property-medellin.png", status: PropertyStatus.PIPELINE, acquisitionDate: "2026-09-01", operationsStartDate: "2028-07-01", purchasePrice: 3800000, buildingImprovements: 1000000, preOpeningCosts: 200000, operatingReserve: 600000, roomCount: 30, startAdr: 210, adrGrowthRate: 0.04, startOccupancy: 0.50, maxOccupancy: 0.78, occupancyRampMonths: 6, occupancyGrowthStep: 0.05, type: "Financed", costRateFB: 0.075, costRateIT: 0.005, cateringBoostPercent: 0.18, exitCapRate: 0.095, acquisitionLTV: 0.60, acquisitionInterestRate: 0.095, acquisitionTermYears: 25, acquisitionClosingCostRate: 0.02, revShareEvents: 0.25, depreciationYears: 20 },
  { ...SEED_PROPERTY_DEFAULTS, name: "Blue Ridge Manor", streetAddress: "275 Elk Mountain Scenic Highway", city: "Asheville", stateProvince: "NC", zipPostalCode: "28804", location: "Blue Ridge Mountains, North Carolina", market: "North America", imageUrl: "/images/property-asheville.png", status: PropertyStatus.PIPELINE, acquisitionDate: "2027-07-01", operationsStartDate: "2028-07-01", purchasePrice: 6000000, buildingImprovements: 1500000, preOpeningCosts: 250000, operatingReserve: 500000, roomCount: 30, startAdr: 375, adrGrowthRate: 0.025, startOccupancy: 0.50, maxOccupancy: 0.80, occupancyRampMonths: 6, occupancyGrowthStep: 0.05, type: "Financed", costRateFB: 0.10, costRateIT: 0.005, cateringBoostPercent: 0.25, exitCapRate: 0.09, acquisitionLTV: 0.60, acquisitionInterestRate: 0.09, acquisitionTermYears: 25, acquisitionClosingCostRate: 0.02, revShareEvents: 0.28 },
];

export const SEED_MEDELLIN_DUPLEX = {
  userId: null,
  name: "Medellin Duplex",
  description: "A stunning two-story luxury duplex apartment in El Poblado, Medellín's most exclusive residential zone. Contemporary open-concept design with double-height ceilings, floating staircase, Calacatta marble kitchen island, and panoramic city and Andes mountain views from floor-to-ceiling windows across 350 square meters on two floors.",
  streetAddress: "Calle 10 #43A-22, El Poblado",
  city: "Medellín",
  stateProvince: "Antioquia",
  zipPostalCode: "050021",
  country: "Colombia",
  location: "El Poblado, Medellín, Colombia",
  market: "Latin America",
  imageUrl: "/images/medellin-duplex-1.jpeg",
  status: PropertyStatus.ACQUIRED,
  acquisitionDate: "2025-03-01",
  operationsStartDate: "2025-09-01",
  purchasePrice: 800000,
  buildingImprovements: 150000,
  landValuePercent: DEFAULT_LAND_VALUE_PERCENT,
  preOpeningCosts: 15000,
  operatingReserve: 60000,
  roomCount: 4,
  startAdr: 1000,
  adrGrowthRate: 0.04,
  startOccupancy: 0.45,
  maxOccupancy: 0.65,
  occupancyRampMonths: 4,
  stabilizationMonths: 12,
  occupancyGrowthStep: 0.04,
  type: "Full Equity",
  willRefinance: "No",
  costRateRooms: 0.14,
  costRateFB: 0.06,
  costRateAdmin: 0.07,
  costRateMarketing: 0.02,
  costRatePropertyOps: 0.04,
  costRateUtilities: 0.04,
  costRateTaxes: 0.018,
  costRateIT: 0.005,
  costRateFFE: 0.03,
  costRateOther: 0.04,
  costRateInsurance: DEFAULT_COST_RATE_INSURANCE,
  revShareEvents: 0.10,
  revShareFB: 0.12,
  revShareOther: 0.06,
  cateringBoostPercent: 0.10,
  exitCapRate: 0.08,
  taxRate: 0.35,
  countryRiskPremium: 0.0275,
  dispositionCommission: DEFAULT_COMMISSION_RATE,
  baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
  incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
  depreciationYears: 20,
  hospitalityType: "extended_stay",
  latitude: 6.2086,
  longitude: -75.5659,
  isActive: true,
};

export const SEED_MEDELLIN_DUPLEX_PHOTOS = [
  { imageUrl: "/images/medellin-duplex-1.jpeg", caption: "Open-concept living and dining area with Calacatta marble island and floating staircase", sortOrder: 0, isHero: true },
  { imageUrl: "/images/medellin-duplex-2.jpeg", caption: "Chef's kitchen with marble waterfall island and panoramic Andes mountain views", sortOrder: 1, isHero: false },
  { imageUrl: "/images/medellin-duplex-3.jpeg", caption: "Master suite with floor-to-ceiling windows overlooking Medellín's skyline and mountains", sortOrder: 2, isHero: false },
];
