// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/funding-tab/EditorialPolish.tsx": () => import("../components/mockups/funding-tab/EditorialPolish.tsx"),
  "./components/mockups/funding-tab/RefinedDensity.tsx": () => import("../components/mockups/funding-tab/RefinedDensity.tsx")
};
