// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kpi-hero/Animated.tsx": () => import("../components/mockups/kpi-hero/Animated.tsx"),
  "./components/mockups/kpi-hero/Bento.tsx": () => import("../components/mockups/kpi-hero/Bento.tsx"),
  "./components/mockups/kpi-hero/Glass.tsx": () => import("../components/mockups/kpi-hero/Glass.tsx"),
  "./components/mockups/kpi-hero/Swiss.tsx": () => import("../components/mockups/kpi-hero/Swiss.tsx"),
  "./components/mockups/funding-tab/EditorialPolish.tsx": () => import("../components/mockups/funding-tab/EditorialPolish.tsx"),
  "./components/mockups/funding-tab/RefinedDensity.tsx": () => import("../components/mockups/funding-tab/RefinedDensity.tsx"),
  "./components/mockups/funding-tab/UsabilityAccessible.tsx": () => import("../components/mockups/funding-tab/UsabilityAccessible.tsx"),
  "./components/mockups/funding-tab/UsabilityAffordance.tsx": () => import("../components/mockups/funding-tab/UsabilityAffordance.tsx"),
  "./components/mockups/funding-tab/UsabilityHierarchy.tsx": () => import("../components/mockups/funding-tab/UsabilityHierarchy.tsx")
};
