import type { RegulatoryProfile } from "../regulatory-data";

export const REGULATORY_PROFILES_NA: Record<string, RegulatoryProfile> = {
  "US": {
    country: "United States",
    countryCode: "US",
    licensing: {
      nationalLicenseRequired: false,
      localPermitRequired: true,
      licenseType: "State/Local Hospitality License, Business License, Liquor License (if applicable)",
      typicalTimeline: "2-6 months (varies significantly by state and municipality)",
      renewalFrequency: "Annual",
      estimatedCost: "$500-$5,000+ depending on jurisdiction and license type",
      notes: "Regulations are primarily STATE and LOCAL level. No single federal hospitality license. Health department permits, fire marshal approval, and certificate of occupancy are universally required. Liquor licenses can take 6-12 months and cost $10,000+ in some states.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-12 months (varies by municipality; can exceed 18 months in dense urban areas)",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "Zoning is exclusively local (city/county). Many jurisdictions require a Conditional Use Permit (CUP) or Special Use Permit for hotel/B&B use in residential zones. NEPA applies to federally funded projects; state equivalents (SEQRA in NY, CEQA in CA) may apply. Historic districts (National Register, local landmarks) impose additional review.",
    },
    buildingCodes: {
      fireCodeStandard: "NFPA 101 Life Safety Code; IBC (International Building Code) adopted by most states",
      adaEquivalent: "ADA (Americans with Disabilities Act) — Title III public accommodations",
      seismicRequirements: true,
      energyEfficiencyCode: "ASHRAE 90.1 / IECC (International Energy Conservation Code); varies by state adoption",
      maxOccupancyRegulation: "Determined by local fire marshal per IBC Chapter 10 occupancy load calculations",
      notes: "ADA compliance is federal and non-negotiable for public accommodations (hotels). Seismic requirements vary by zone — critical in CA, WA, OR, parts of UT, NY (Zone 2A). Sprinkler systems required for hotels in most jurisdictions.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "No general restrictions on foreign ownership of real property. CFIUS review may apply to acquisitions near sensitive government installations. Some states restrict agricultural land ownership by foreign entities.",
      repatriationRestrictions: false,
      treatyProtections: "Bilateral Investment Treaties with 40+ countries; USMCA (with Canada/Mexico)",
      notes: "FIRPTA (Foreign Investment in Real Property Tax Act) imposes a 15% withholding on real property dispositions by foreign persons. Consult tax counsel for structuring.",
    },
    labor: {
      minimumWage: "$7.25/hr federal; many states significantly higher (NY $16.00, CA $16.00, UT $7.25)",
      mandatoryBenefits: "Social Security/Medicare (employer share ~7.65%), unemployment insurance, workers' comp. No federal mandate for health insurance <50 employees (ACA).",
      terminationRules: "At-will employment in most states (exceptions: MT). WARN Act for mass layoffs (60-day notice for 100+ employees).",
      unionPrevalence: "Low to moderate in hospitality. UNITE HERE active in major metro hotels. Right-to-work laws in 27 states.",
      notes: "Tipped employee minimum wage as low as $2.13/hr federally (with tip credit). State laws vary widely. H-2B visa program available for seasonal hospitality workers.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "https://www.sba.gov/business-guide/launch-your-business/apply-for-licenses-and-permits",
      "https://www.ada.gov/topics/title-iii-public-accommodations/",
      "https://www.irs.gov/individuals/international-taxpayers/firpta",
      "https://www.dol.gov/agencies/whd/minimum-wage/state",
      "NFPA 101 Life Safety Code (2024 edition)",
      "International Building Code (IBC) 2024",
    ],
    usStateOverrides: {
      "New York": {
        licensing: {
          nationalLicenseRequired: false,
          localPermitRequired: true,
          licenseType: "NYC Department of Buildings Certificate of Occupancy, NYS Department of Health Permit, SLA Liquor License",
          typicalTimeline: "4-12 months (NYC is notoriously slow; expediter recommended)",
          renewalFrequency: "Annual for most permits; SLA license every 3 years",
          estimatedCost: "$5,000-$25,000+ (NYC); $1,000-$5,000 (upstate)",
          notes: "NYC requires Special Permit from City Planning Commission for hotels in many zoning districts. Multiple Dwelling Law (MDL) may apply for buildings with 3+ units. NYC hotel development effectively paused in many areas due to City of Yes zoning changes — consult current NYC DCP guidance.",
        },
        zoning: {
          residentialToCommercialAllowed: true,
          zoningChangeRequired: true,
          typicalZoningTimeline: "6-18 months in NYC (ULURP process if rezoning needed); 3-6 months upstate",
          environmentalReviewRequired: true,
          historicPreservation: true,
          notes: "NYC: ULURP (Uniform Land Use Review Procedure) required for rezoning — 7-month minimum. SEQRA (State Environmental Quality Review Act) applies statewide. NYC Landmarks Preservation Commission review required in historic districts (e.g., Greenwich Village, Brooklyn Heights). Upstate: local planning board approval typically faster.",
        },
        buildingCodes: {
          fireCodeStandard: "NYC Building Code (based on IBC with NYC-specific amendments) + FDNY requirements",
          adaEquivalent: "ADA + NYC Local Law 58 (stricter accessibility requirements)",
          seismicRequirements: true,
          energyEfficiencyCode: "NYC Local Law 97 (carbon emissions limits for buildings >25,000 sq ft) + NYStretch Energy Code",
          maxOccupancyRegulation: "NYC Building Code Chapter 10; FDNY Certificate of Fitness required for certain occupancy types",
          notes: "NYC Local Law 97 imposes aggressive carbon penalties starting 2024 for large buildings. Hotel conversions must comply with current energy code, which may require significant HVAC/envelope upgrades. Sprinkler systems mandatory in all hotels.",
        },
      },
      "Utah": {
        licensing: {
          nationalLicenseRequired: false,
          localPermitRequired: true,
          licenseType: "Utah DABC Liquor License (if applicable), local business license, health department food service permit",
          typicalTimeline: "2-4 months",
          renewalFrequency: "Annual",
          estimatedCost: "$500-$3,000",
          notes: "Utah has restrictive liquor laws — DABC (Department of Alcoholic Beverage Control) controls all liquor licenses with a limited quota system. Hotel liquor licenses are available but limited. Planning around liquor service is critical for F&B revenue projections.",
        },
        zoning: {
          residentialToCommercialAllowed: true,
          zoningChangeRequired: true,
          typicalZoningTimeline: "2-6 months",
          environmentalReviewRequired: true,
          historicPreservation: false,
          notes: "Utah counties vary significantly. Summit County (Park City area) has strict resort zone requirements. Rural counties are generally more permissive. Water rights are a critical consideration — verify water availability before any conversion.",
        },
        buildingCodes: {
          fireCodeStandard: "IBC/IFC as adopted by Utah (with state amendments)",
          adaEquivalent: "ADA (federal) — no additional state overlay",
          seismicRequirements: true,
          energyEfficiencyCode: "IECC 2021 as adopted by Utah",
          maxOccupancyRegulation: "Local fire marshal per IBC Chapter 10",
          notes: "Wasatch Fault Zone runs through SLC and surrounding areas — seismic design category D. Mountain properties may have additional snow load requirements. Wildfire interface zone considerations in foothill/mountain areas.",
        },
      },
    },
  },

  "MX": {
    country: "Mexico",
    countryCode: "MX",
    licensing: {
      nationalLicenseRequired: false,
      localPermitRequired: true,
      licenseType: "Licencia de Funcionamiento (municipal), SECTUR registration, health permits (COFEPRIS)",
      typicalTimeline: "2-4 months",
      renewalFrequency: "Annual for most municipal licenses",
      estimatedCost: "$1,000-$5,000 depending on municipality and property size",
      notes: "SECTUR (Secretaría de Turismo) registration is recommended but not always mandatory. Municipal licencia de funcionamiento is required everywhere. COFEPRIS health permits required for food service. States like Quintana Roo (Cancún) have additional tourism-specific requirements.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-8 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "Zoning governed by municipal PDU (Plan de Desarrollo Urbano). Environmental impact assessment (MIA — Manifestación de Impacto Ambiental) required through SEMARNAT for projects in coastal or protected zones. INAH (Instituto Nacional de Antropología e Historia) review required for properties in historic zones or near archaeological sites.",
    },
    buildingCodes: {
      fireCodeStandard: "NOM-002-STPS (workplace fire safety); local building regulations vary by state",
      adaEquivalent: "NOM-030-SSA3-2013 (accessibility for persons with disabilities)",
      seismicRequirements: true,
      energyEfficiencyCode: "NOM-008-ENER (building envelope); NOM-020-ENER (thermal insulation for residential — commercial standards vary)",
      maxOccupancyRegulation: "Determined by local Protección Civil inspection",
      notes: "Mexico City, Oaxaca, and Pacific coast are high seismic zones. Mexico's seismic code was significantly updated after the 2017 earthquake. All states require a Director Responsable de Obra (licensed professional) to oversee construction.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "Direct ownership prohibited in 'restricted zone' (50km from coast, 100km from border). Foreign investors must use a fideicomiso (bank trust) for coastal/border properties — effectively grants full use and ownership rights for 50-year renewable terms.",
      repatriationRestrictions: false,
      treatyProtections: "USMCA (US-Mexico-Canada Agreement); numerous BITs",
      notes: "Fideicomiso is a well-established, secure legal mechanism — virtually all foreign-owned coastal hotels use it. Cost: ~$2,000-$5,000 setup + ~$1,000-$2,000/year bank fees. Mexican corporation (S.A. de C.V. or S. de R.L.) is another common structure for larger investments.",
    },
    labor: {
      minimumWage: "MXN 278.80/day general; MXN 419.88/day in northern border free zone (2026)",
      mandatoryBenefits: "IMSS (health/pension — employer ~25-30% of base), INFONAVIT (housing fund 5%), vacation premium (25% of vacation days pay), aguinaldo (15 days pay minimum), profit sharing (PTU — 10% of pre-tax profits)",
      terminationRules: "Just cause required (Ley Federal del Trabajo Art. 47). Unjust termination triggers 3 months' salary + 20 days/year tenure + accrued benefits. Reinstatement can be ordered.",
      unionPrevalence: "Moderate. 2019 labor reform strengthened union democracy. Hospitality sector has active unions in resort areas.",
      notes: "PTU (profit sharing) at 10% of pre-tax profits is a significant cost — capped at 3 months' salary or average of last 3 years, whichever is more favorable to the worker (2021 reform). Factor into financial models. Total employer payroll burden approximately 35-40% above base salary.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "Ley Federal del Trabajo (Mexico)",
      "https://www.gob.mx/sectur",
      "https://www.gob.mx/semarnat",
      "COFEPRIS regulations",
      "Ley de Inversión Extranjera",
    ],
  },

  "CA": {
    country: "Canada",
    countryCode: "CA",
    licensing: {
      nationalLicenseRequired: false,
      localPermitRequired: true,
      licenseType: "Provincial Tourism Operator License, Municipal Business Licence, Liquor License (provincial)",
      typicalTimeline: "2-4 months",
      renewalFrequency: "Annual",
      estimatedCost: "CAD $500-$5,000 depending on province and municipality",
      notes: "Tourism licensing is provincial. BC, Ontario, Quebec each have distinct regimes. Liquor licenses are provincial (AGCO in Ontario, BCLDB in BC, RACJ in Quebec). Health inspection and food safety certification required for F&B.",
    },
    zoning: {
      residentialToCommercialAllowed: true,
      zoningChangeRequired: true,
      typicalZoningTimeline: "3-9 months",
      environmentalReviewRequired: true,
      historicPreservation: true,
      notes: "Zoning is municipal. Requires rezoning application or development variance permit. Environmental Assessment Act (federal and provincial) may apply. Heritage designation (federal Historic Sites, provincial registries) restricts alterations.",
    },
    buildingCodes: {
      fireCodeStandard: "National Building Code of Canada (NBC) + National Fire Code of Canada (NFC); provinces adopt with amendments",
      adaEquivalent: "CSA B651 (Accessible Design for the Built Environment); provincial human rights codes; Accessibility for Ontarians with Disabilities Act (AODA) in Ontario",
      seismicRequirements: true,
      energyEfficiencyCode: "National Energy Code of Canada for Buildings (NECB); BC Step Code; Toronto Green Standard",
      maxOccupancyRegulation: "Provincial fire marshal per NBC Part 3 occupancy classifications",
      notes: "Seismic requirements significant in BC (Vancouver, Victoria). Step Code in BC is among the most aggressive energy codes in North America. Bilingual signage may be required in Quebec.",
    },
    foreignInvestment: {
      foreignOwnershipAllowed: true,
      ownershipRestrictions: "Prohibition on Purchase of Residential Property by Non-Canadians Act (2023-2027) restricts non-Canadian purchase of residential property. Exemptions exist for commercial-purpose properties. Consult current status — law has been extended/amended multiple times.",
      repatriationRestrictions: false,
      treatyProtections: "USMCA; Canada-EU CETA; numerous BITs",
      notes: "BC and Ontario impose additional Foreign Buyer Taxes (20% in BC, 25% in Ontario) on residential property purchases by foreign nationals. Commercial/hotel properties may be exempt depending on classification. Withholding tax on rental income for non-residents (25%, reducible by treaty).",
    },
    labor: {
      minimumWage: "CAD $16.00-$17.40/hr (varies by province; BC $17.40, Ontario $16.55, Alberta $15.00)",
      mandatoryBenefits: "CPP/QPP (employer ~5.95%), EI (employer ~2.21%), provincial health insurance (employer payroll tax varies), vacation (min 2 weeks), statutory holidays",
      terminationRules: "Provincial employment standards set minimum notice periods. Common law reasonable notice applies (can be substantial — months of pay depending on tenure). Federally regulated workers under Canada Labour Code.",
      unionPrevalence: "Moderate. UNITE HERE Canada active in hotel sector, particularly in major cities.",
      notes: "Provincial payroll taxes vary significantly — Ontario Employer Health Tax (EHT), BC Employer Health Tax, Quebec HSF. Total employer burden approximately 15-25% above base salary depending on province.",
    },
    lastUpdated: "2026-04-13",
    sources: [
      "National Building Code of Canada 2020",
      "Investment Canada Act",
      "Prohibition on Purchase of Residential Property by Non-Canadians Act",
      "Provincial employment standards legislation",
    ],
  },
};
