import { db } from "../db";
import { knowledgeRegistry, countryEconomicData } from "@workspace/db";
import { logger } from "../logger";

// ---------------------------------------------------------------------------
// 8 canonical AI knowledge assets. `id` is the natural key (slug); updates
// to display fields take effect on next boot via onConflictDoUpdate.
// `last_refreshed_at` is excluded from the conflict target so live timestamps
// are never overwritten by the seed.
// ---------------------------------------------------------------------------
const KNOWLEDGE_REGISTRY_SEEDS: typeof knowledgeRegistry.$inferInsert[] = [
  {
    id: "market-research",
    displayName: "Market Research",
    description: "Synthesized hospitality market intelligence: ADR benchmarks, occupancy trends, demand drivers, and competitive positioning by property and market.",
    howBuilt: "Generated by the Market Research Specialist via multi-model LLM synthesis and web research, then embedded into the market-research vector namespace.",
    sourceDescription: "Perplexity Sonar, Tavily web search, Anthropic Claude synthesis",
    renewalMechanism: "Triggered per-property from the research engine or via the Analyst button in the Knowledge Registry.",
    assetType: "vector_namespace",
    assetRef: "market-research",
  },
  {
    id: "comparables",
    displayName: "Comparables",
    description: "Hotel and STR comp-set profiles with pricing, ratings, and positioning data for semantic search during property analysis.",
    howBuilt: "Scraped from Booking.com, Airbnb, and Hotels.com via Apify actors, processed by the Comparables Specialist, and embedded into the comparables vector namespace.",
    sourceDescription: "Apify scrapers (Booking.com, Airbnb, Hotels.com), Google Hotels",
    renewalMechanism: "Triggered per-property from the research engine or via the Analyst button in the Knowledge Registry.",
    assetType: "vector_namespace",
    assetRef: "comparables",
  },
  {
    id: "knowledge-base",
    displayName: "Knowledge Base",
    description: "Curated hospitality industry knowledge: regulations, brand standards, operating practices, and investment frameworks.",
    howBuilt: "Ingested from curated documents, industry reports, and structured reference materials via the Knowledge Base Specialist and embedded into the knowledge-base vector namespace.",
    sourceDescription: "Curated documents, STR/CBRE/HVS industry reports, regulatory references",
    renewalMechanism: "Triggered manually via the Analyst button in the Knowledge Registry.",
    assetType: "vector_namespace",
    assetRef: "knowledge-base",
  },
  {
    id: "assumption-guidance",
    displayName: "Assumption Guidance",
    description: "Historical guidance records that capture what the Analyst recommended for each property, used to inform future guidance requests.",
    howBuilt: "Written automatically by the Analyst after each per-property guidance run. Each run appends new chunks to the assumption-guidance namespace.",
    sourceDescription: "H+ Analyst per-property guidance runs",
    renewalMechanism: "Populated automatically as a side-effect of per-entity analyst runs. No portfolio-wide regeneration path exists.",
    assetType: "vector_namespace",
    assetRef: "assumption-guidance",
  },
  {
    id: "capital-raise",
    displayName: "Capital Raise Benchmarks",
    description: "Reference ranges for equity raise, preferred return, GP/LP splits, and capital structure benchmarks by property type and market.",
    howBuilt: "Seeded from industry reports (HVS, CBRE, PKF) and maintained via the Analyst benchmark regeneration workflow.",
    sourceDescription: "HVS, CBRE, PKF industry benchmark reports",
    renewalMechanism: "Triggered via the Analyst button in the Knowledge Registry.",
    assetType: "benchmark_table",
    assetRef: "capital-raise",
  },
  {
    id: "exit-multiples",
    displayName: "Exit Multiples",
    description: "Cap rate and exit multiple benchmarks by property type, market tier, and hold period for underwriting terminal value assumptions.",
    howBuilt: "Seeded from CBRE, JLL, and HVS hotel transaction data and maintained via the Analyst benchmark regeneration workflow.",
    sourceDescription: "CBRE, JLL, HVS hotel transaction benchmarks",
    renewalMechanism: "Triggered via the Analyst button in the Knowledge Registry.",
    assetType: "benchmark_table",
    assetRef: "exit-multiples",
  },
  {
    id: "reference-brands",
    displayName: "Reference Brands",
    description: "Brand comp-set reference library with hotel brand profiles, positioning tiers, and typical performance metrics for comp analysis.",
    howBuilt: "Seeded from industry brand directories and STR comp-set data, stored in the reference_brands table.",
    sourceDescription: "STR brand comps, JLL hospitality brand research",
    renewalMechanism: "Triggered via the Analyst button in the Knowledge Registry.",
    assetType: "benchmark_brands",
    assetRef: "reference-brands",
  },
  {
    id: "country-data",
    displayName: "Country Economic Data",
    description: "Macro-economic indicators (inflation, FX rates, GDP growth, interest rates) for the four primary markets: US, MX, CO, BR.",
    howBuilt: "Fetched from FRED (US rates), Frankfurter ECB (FX rates), and IMF/World Bank (GDP growth, international rates) on demand.",
    sourceDescription: "FRED API, Frankfurter ECB, IMF/World Bank Open Data",
    renewalMechanism: "Triggered via the Analyst button on the Country Economic Data sub-page.",
    assetType: "country_data",
    assetRef: "country-economic-data",
  },
  {
    id: "vendor-passthrough-costs",
    displayName: "National Vendor Pass-Through Costs",
    description: "National hospitality benchmarks for vendor pass-through costs per service line (marketing, IT, accounting, reservations, housekeeping, maintenance, revenue management, F&B, branding, performance bonus), expressed as % of total revenue.",
    howBuilt: "Fetched by minion Gaetano via Exa neural search over STR Global, CBRE, HVS, and PKF 2024 annual benchmark reports. Falls back to sourced industry anchors when search yields no parseable values.",
    sourceDescription: "Exa neural search: STR HOST 2024, CBRE Hotels Americas Research 2024, HVS Management Contract Benchmarks 2024, PKF Hospitality Research 2024",
    renewalMechanism: "Triggered daily by Pietro scheduler (minion Gaetano) or on demand via the Analyst button in the Knowledge Registry.",
    assetType: "benchmark_table",
    assetRef: "vendor-passthrough-costs",
  },
  {
    id: "mgmt-co-markup-factors",
    displayName: "National Mgmt Co Markup Factors",
    description: "National benchmarks for Management Company markup factors per service line — the Mgmt Co's margin above vendor cost, expressed as % of total revenue (additive on top of pass-through costs).",
    howBuilt: "Fetched by minion Renato via Exa neural search over HVS, CBRE, and PKF hotel management agreement fee benchmarks. Falls back to sourced industry anchors when search yields no parseable values.",
    sourceDescription: "Exa neural search: HVS Management Contract Benchmarks 2024, CBRE Hotels Americas Research 2024, PKF Hospitality Research 2024",
    renewalMechanism: "Triggered daily by Pietro scheduler (minion Renato) or on demand via the Analyst button in the Knowledge Registry.",
    assetType: "benchmark_table",
    assetRef: "mgmt-co-markup-factors",
  },
];

// Last-known seed values for country_economic_data. Inserted once on first
// boot via onConflictDoNothing so live values from regeneration are preserved.
const COUNTRY_SEED_VALUES: typeof countryEconomicData.$inferInsert[] = [
  {
    countryCode: "US",
    countryName: "United States",
    inflationRate: "3.2",
    fxRateToUsd: "1.0",
    gdpGrowthRate: "2.5",
    interestRate: "5.33",
    sourceNotes: "FRED: CPI (3.2%), Fed Funds (5.33%); World Bank GDP (2.5%)",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    inflationRate: "4.8",
    fxRateToUsd: "0.058",
    gdpGrowthRate: "1.5",
    interestRate: "11.0",
    sourceNotes: "Frankfurter ECB FX; World Bank GDP; Banxico interest rate",
  },
  {
    countryCode: "CO",
    countryName: "Colombia",
    inflationRate: "6.9",
    fxRateToUsd: "0.00025",
    gdpGrowthRate: "1.6",
    interestRate: "12.75",
    sourceNotes: "Frankfurter ECB FX; World Bank GDP; BanRep interest rate",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    inflationRate: "4.5",
    fxRateToUsd: "0.20",
    gdpGrowthRate: "2.9",
    interestRate: "10.5",
    sourceNotes: "Frankfurter ECB FX; World Bank GDP; BCB Selic rate",
  },
];

export async function seedKnowledgeRegistry(): Promise<void> {
  logger.info(`Seeding knowledge registry (${KNOWLEDGE_REGISTRY_SEEDS.length} assets)...`, "seed");

  await db
    .insert(knowledgeRegistry)
    .values(KNOWLEDGE_REGISTRY_SEEDS)
    .onConflictDoUpdate({
      target: knowledgeRegistry.id,
      set: {
        displayName: knowledgeRegistry.displayName,
        description: knowledgeRegistry.description,
        howBuilt: knowledgeRegistry.howBuilt,
        sourceDescription: knowledgeRegistry.sourceDescription,
        renewalMechanism: knowledgeRegistry.renewalMechanism,
        // assetType and assetRef are structural — do not overwrite on conflict
      },
    });

  logger.info(`Knowledge registry seed complete`, "seed");
}

export async function seedCountryEconomicDataIfEmpty(): Promise<void> {
  // Use onConflictDoNothing so live values written by the regeneration endpoint
  // are never overwritten with stale seed values on subsequent boots.
  await db
    .insert(countryEconomicData)
    .values(COUNTRY_SEED_VALUES)
    .onConflictDoNothing();

  logger.info(`Country economic data seed complete (last-known values, skipped if rows exist)`, "seed");
}
