/**
 * AnalystProgressHUD — concept mockup.
 *
 * Floating fixed-position rectangle that appears in front of page content
 * while the Analyst AI agent is processing. Uses:
 *   • Phase-aware rotating messages generated by Claude Opus
 *   • hsl(var(--accent-pop)) amber throughout (H+ theme token)
 *   • JetBrains Mono character-art progress bar with active-edge pulse
 *   • Framer Motion slide-up entrance, blur crossfade line transitions
 */
import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";

// ── Phase definitions & Claude Opus-generated messages ────────────────────

const PHASES = [
  {
    id: "SOURCING",
    label: "sourcing data",
    range: [0, 20] as [number, number],
    lines: [
      "Pulling STR trend reports for comp set",
      "Querying FRED for 10Y treasury spreads",
      "Ingesting CBRE cap rate survey Q3",
      "Tapping HVS transaction database",
      "Streaming RevPAR by chain scale",
      "Fetching USALI-aligned P&L statements",
      "Parsing brand STAR reports",
      "Sourcing market-level ADR histories",
    ],
  },
  {
    id: "CROSS_REF",
    label: "cross-referencing",
    range: [20, 40] as [number, number],
    lines: [
      "Aligning comp set against subject asset",
      "Reconciling STR data with brand reports",
      "Mapping NOI margins across vintages",
      "Triangulating ADR with occupancy curves",
      "Matching trade comps by RevPAR tier",
      "Cross-checking cap rates by MSA",
      "Linking GOP flow-through to labor index",
      "Bridging owner books to USALI standard",
    ],
  },
  {
    id: "CALIBRATING",
    label: "calibrating",
    range: [40, 60] as [number, number],
    lines: [
      "Adjusting RevPAR penetration index",
      "Tuning expense ratios to market median",
      "Recalibrating exit cap assumptions",
      "Stress-testing DSCR at SOFR plus 350",
      "Normalizing seasonality in monthly ADR",
      "Reweighting comp set by proximity",
      "Refining FF&E reserve to 4 percent",
      "Indexing wages to BLS hospitality data",
    ],
  },
  {
    id: "SYNTHESIZING",
    label: "synthesizing",
    range: [60, 80] as [number, number],
    lines: [
      "Modeling 10-year stabilized NOI",
      "Drafting going-in yield narrative",
      "Composing hold-period IRR scenarios",
      "Building waterfall to LP and GP tiers",
      "Framing GOP margin trajectory",
      "Sizing senior debt against DSCR floor",
      "Mapping value-add upside to ADR lift",
      "Articulating exit cap sensitivity",
    ],
  },
  {
    id: "VALIDATING",
    label: "validating",
    range: [80, 100] as [number, number],
    lines: [
      "Auditing RevPAR against STR rebench",
      "Verifying cap rate against recent trades",
      "Checking NOI for USALI compliance",
      "Reconciling DSCR under downside case",
      "Sanity-checking ADR versus comp ceiling",
      "Reviewing flow-through math line by line",
      "Confirming reserve assumptions hold",
      "Locking sources and citation trail",
    ],
  },
] as const;

const BAR_SEGMENTS = 22;

// ── Helpers ────────────────────────────────────────────────────────────────

function formatElapsed(seconds: number): string {
  if (seconds < 60) return `${seconds}s`;
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}m ${s.toString().padStart(2, "0")}s`;
}

function getPhase(progress: number) {
  return (
    PHASES.find(p => progress >= p.range[0] && progress < p.range[1]) ??
    PHASES[PHASES.length - 1]
  );
}

function useElapsedTimer(active: boolean) {
  const [elapsed, setElapsed] = useState(0);
  const startRef = useRef(Date.now());
  useEffect(() => {
    if (!active) return;
    startRef.current = Date.now();
    const id = setInterval(
      () => setElapsed(Math.floor((Date.now() - startRef.current) / 1000)),
      1000
    );
    return () => clearInterval(id);
  }, [active]);
  return elapsed;
}

/** Rotates through the current phase's lines every intervalMs. */
function usePhaseLines(progress: number, intervalMs = 3200) {
  const [lineIndex, setLineIndex] = useState(0);
  const prevPhaseId = useRef<string>("");

  const phase = getPhase(progress);

  // Reset index when phase changes
  useEffect(() => {
    if (phase.id !== prevPhaseId.current) {
      prevPhaseId.current = phase.id;
      setLineIndex(0);
    }
  }, [phase.id]);

  useEffect(() => {
    const id = setInterval(
      () => setLineIndex(i => (i + 1) % phase.lines.length),
      intervalMs
    );
    return () => clearInterval(id);
  }, [phase.id, phase.lines.length, intervalMs]);

  return { phase, line: phase.lines[lineIndex] };
}

// ── Character-art progress bar ─────────────────────────────────────────────

function ProgressBar({ progress }: { progress: number }) {
  const filled = Math.round(
    (Math.min(100, Math.max(0, progress)) / 100) * BAR_SEGMENTS
  );
  const pct = Math.round(progress);

  return (
    <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
      <span
        style={{
          fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
          fontSize: "11px",
          letterSpacing: "0.04em",
          lineHeight: 1,
        }}
        aria-hidden
      >
        {Array.from({ length: BAR_SEGMENTS }, (_, i) => {
          const isFilled = i < filled;
          const isLeading = i === filled - 1 && filled > 0;

          if (isLeading) {
            return (
              <motion.span
                key={i}
                animate={{ opacity: [1, 0.3, 1] }}
                transition={{ duration: 1.0, repeat: Infinity, ease: "easeInOut" }}
                style={{ color: "hsl(var(--accent-pop))" }}
              >
                ●
              </motion.span>
            );
          }
          return (
            <span
              key={i}
              style={{
                color: isFilled ? "hsl(var(--accent-pop))" : "rgba(0,0,0,0.12)",
              }}
            >
              {isFilled ? "●" : "○"}
            </span>
          );
        })}
      </span>
      <span
        style={{
          fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
          fontSize: "11px",
          color: "rgba(0,0,0,0.38)",
          minWidth: "2.2rem",
          fontVariantNumeric: "tabular-nums",
        }}
      >
        {pct}%
      </span>
    </div>
  );
}

// ── Animated 4-pointed Claude-style sparkle ────────────────────────────────

function AnimatedSparkle({ size = 18 }: { size?: number }) {
  return (
    <span
      style={{
        position: "relative",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        width: size,
        height: size,
        flexShrink: 0,
      }}
    >
      {/* Outer star — clockwise */}
      <motion.svg
        width={size}
        height={size}
        viewBox="0 0 24 24"
        aria-hidden
        animate={{ rotate: 360 }}
        transition={{ duration: 6, repeat: Infinity, ease: "linear" }}
        style={{ position: "absolute" }}
      >
        <path
          d="M12 2 C12 7 17 12 22 12 C17 12 12 17 12 22 C12 17 7 12 2 12 C7 12 12 7 12 2 Z"
          fill="hsl(var(--accent-pop))"
        />
      </motion.svg>
      {/* Inner star — counter-clockwise */}
      <motion.svg
        width={size * 0.44}
        height={size * 0.44}
        viewBox="0 0 24 24"
        aria-hidden
        animate={{ rotate: -360 }}
        transition={{ duration: 4, repeat: Infinity, ease: "linear" }}
        style={{ position: "absolute" }}
      >
        <path
          d="M12 2 C12 7 17 12 22 12 C17 12 12 17 12 22 C12 17 7 12 2 12 C7 12 12 7 12 2 Z"
          fill="rgba(255,255,255,0.92)"
        />
      </motion.svg>
    </span>
  );
}

// ── The HUD ────────────────────────────────────────────────────────────────

function AnalystHUD({ progress, visible }: { progress: number; visible: boolean }) {
  const elapsed = useElapsedTimer(visible);
  const { phase, line } = usePhaseLines(progress);

  return (
    <AnimatePresence>
      {visible && (
        <motion.div
          key="analyst-hud"
          initial={{ opacity: 0, y: 18, scale: 0.97 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 14, scale: 0.96 }}
          transition={{ duration: 0.38, ease: [0.16, 1, 0.3, 1] }}
          style={{
            position: "fixed",
            bottom: "24px",
            right: "24px",
            width: "352px",
            zIndex: 9999,
            background: "rgba(255,255,255,0.97)",
            backdropFilter: "blur(20px) saturate(1.8)",
            WebkitBackdropFilter: "blur(20px) saturate(1.8)",
            borderRadius: "8px",
            boxShadow:
              "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
            border: "1px solid hsl(var(--border))",
            overflow: "hidden",
          }}
        >
          {/* Subtle left rule */}
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              bottom: 0,
              width: "3px",
              background: "rgba(0,0,0,0.07)",
              borderRadius: "11px 0 0 11px",
            }}
          />

          <div
            style={{
              padding: "13px 16px 14px",
              display: "flex",
              flexDirection: "column",
              gap: "9px",
            }}
          >
            {/* Row 1: sparkle · "Analyst" · phase label · elapsed */}
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
              }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                <AnimatedSparkle size={18} />
                <span
                  style={{
                    fontSize: "12px",
                    fontWeight: 600,
                    color: "rgba(0,0,0,0.82)",
                    letterSpacing: "0.01em",
                    fontFamily: "'IBM Plex Sans', system-ui, sans-serif",
                  }}
                >
                  Analyst
                </span>
                <span
                  style={{
                    fontSize: "11px",
                    color: "rgba(0,0,0,0.2)",
                    fontFamily: "'IBM Plex Sans', system-ui, sans-serif",
                  }}
                >
                  ·
                </span>
                {/* Phase label — crossfades when phase changes */}
                <AnimatePresence mode="wait" initial={false}>
                  <motion.span
                    key={phase.id}
                    initial={{ opacity: 0, filter: "blur(4px)" }}
                    animate={{ opacity: 1, filter: "blur(0px)" }}
                    exit={{ opacity: 0, filter: "blur(4px)" }}
                    transition={{ duration: 0.35, ease: "easeOut" }}
                    style={{
                      fontSize: "11px",
                      color: "rgba(0,0,0,0.5)",
                      fontFamily: "'IBM Plex Sans', system-ui, sans-serif",
                      fontWeight: 500,
                    }}
                  >
                    {phase.label}
                  </motion.span>
                </AnimatePresence>
              </div>

              {elapsed >= 2 && (
                <motion.span
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  style={{
                    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
                    fontSize: "11px",
                    color: "rgba(0,0,0,0.35)",
                    fontVariantNumeric: "tabular-nums",
                  }}
                >
                  {formatElapsed(elapsed)}
                </motion.span>
              )}
            </div>

            {/* Row 2: rotating intelligence line */}
            <div
              style={{ overflow: "hidden", height: "15px", position: "relative" }}
            >
              <AnimatePresence mode="wait" initial={false}>
                <motion.span
                  key={line}
                  initial={{ opacity: 0, y: 7, filter: "blur(3px)" }}
                  animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                  exit={{ opacity: 0, y: -7, filter: "blur(3px)" }}
                  transition={{ duration: 0.38, ease: "easeOut" }}
                  style={{
                    display: "block",
                    fontSize: "11px",
                    color: "rgba(0,0,0,0.42)",
                    fontFamily: "'IBM Plex Sans', system-ui, sans-serif",
                    whiteSpace: "nowrap",
                    overflow: "hidden",
                    textOverflow: "ellipsis",
                  }}
                >
                  {line}
                </motion.span>
              </AnimatePresence>
            </div>

            {/* Row 3: character-art bar */}
            <ProgressBar progress={progress} />
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// ── Demo wrapper ───────────────────────────────────────────────────────────

export default function AnalystProgressHUDDemo() {
  const [progress, setProgress] = useState(4);
  const [visible, setVisible] = useState(true);
  const [done, setDone] = useState(false);

  useEffect(() => {
    if (!visible || done) return;
    const id = setInterval(() => {
      setProgress(p => {
        if (p >= 100) {
          clearInterval(id);
          setDone(true);
          setTimeout(() => {
            setVisible(false);
            setTimeout(() => {
              setProgress(4);
              setDone(false);
              setVisible(true);
            }, 2000);
          }, 1000);
          return 100;
        }
        return Math.min(100, p + (Math.random() * 2.2 + 0.5));
      });
    }, 380);
    return () => clearInterval(id);
  }, [visible, done]);

  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#f0f1f4",
        position: "relative",
        overflow: "hidden",
      }}
    >
      {/* Simulated page content — dimmed to focus attention on HUD */}
      <div
        style={{
          opacity: 0.52,
          padding: "28px 32px",
          display: "flex",
          flexDirection: "column",
          gap: "20px",
          userSelect: "none",
          pointerEvents: "none",
        }}
      >
        {/* Header bar */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "12px",
            background: "#fff",
            borderRadius: 10,
            padding: "12px 16px",
            boxShadow: "0 1px 3px rgba(0,0,0,0.07)",
          }}
        >
          <div
            style={{ width: 28, height: 28, borderRadius: 7, background: "hsl(var(--accent-pop))" }}
          />
          <div style={{ width: 160, height: 13, borderRadius: 4, background: "#e2e3e8" }} />
          <div style={{ width: 90, height: 13, borderRadius: 4, background: "#ebebef", marginLeft: 24 }} />
          <div style={{ width: 90, height: 13, borderRadius: 4, background: "#ebebef" }} />
          <div style={{ marginLeft: "auto", width: 76, height: 30, borderRadius: 6, background: "#f3f4f6", border: "1px solid #e2e3e8" }} />
          <div style={{ width: 76, height: 30, borderRadius: 6, background: "hsl(var(--accent-pop) / 0.15)", border: "1px solid hsl(var(--accent-pop) / 0.3)" }} />
        </div>

        {/* KPI cards */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12 }}>
          {[
            { label: "RevPAR", val: "$187", delta: "+12%" },
            { label: "ADR", val: "$248", delta: "+8%" },
            { label: "Occupancy", val: "75.4%", delta: "+3%" },
            { label: "NOI", val: "$2.1M", delta: "+18%" },
          ].map(({ label, val, delta }) => (
            <div
              key={label}
              style={{
                background: "#fff",
                border: "1px solid #e6e7ec",
                borderRadius: 10,
                padding: "14px 16px",
                boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
              }}
            >
              <div style={{ fontSize: 11, color: "#9ca3af", marginBottom: 6, fontFamily: "system-ui" }}>{label}</div>
              <div style={{ fontSize: 20, fontWeight: 700, color: "#111", fontFamily: "system-ui", marginBottom: 4 }}>{val}</div>
              <div style={{ fontSize: 11, color: "#22c55e", fontFamily: "system-ui" }}>{delta}</div>
            </div>
          ))}
        </div>

        {/* Two-column content */}
        <div style={{ display: "grid", gridTemplateColumns: "2fr 1fr", gap: 12 }}>
          <div style={{ background: "#fff", border: "1px solid #e6e7ec", borderRadius: 10, padding: "20px", height: 220, boxShadow: "0 1px 3px rgba(0,0,0,0.05)" }}>
            <div style={{ width: 140, height: 12, borderRadius: 3, background: "#e9eaee", marginBottom: 18 }} />
            {[100, 72, 88, 61, 94, 53].map((w, i) => (
              <div key={i} style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
                <div style={{ width: 28, height: 8, borderRadius: 2, background: "#f0f1f4" }} />
                <div style={{ flex: 1, height: 8, background: "#f0f1f4", borderRadius: 4, overflow: "hidden" }}>
                  <div style={{ width: `${w}%`, height: "100%", background: "hsl(var(--accent-pop) / 0.5)", borderRadius: 4 }} />
                </div>
              </div>
            ))}
          </div>
          <div style={{ background: "#fff", border: "1px solid #e6e7ec", borderRadius: 10, padding: "18px", boxShadow: "0 1px 3px rgba(0,0,0,0.05)" }}>
            <div style={{ width: 90, height: 12, borderRadius: 3, background: "#e9eaee", marginBottom: 16 }} />
            {[1, 2, 3, 4].map(i => (
              <div key={i} style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
                <div style={{ width: 28, height: 28, borderRadius: 7, background: "#f0f1f4", flexShrink: 0 }} />
                <div>
                  <div style={{ width: 88, height: 9, borderRadius: 2, background: "#e4e5ea", marginBottom: 5 }} />
                  <div style={{ width: 54, height: 8, borderRadius: 2, background: "#eeeff3" }} />
                </div>
                <div style={{ marginLeft: "auto", width: 44, height: 9, borderRadius: 2, background: "#e4e5ea" }} />
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* The floating HUD */}
      <AnalystHUD progress={progress} visible={visible} />
    </div>
  );
}
