export const CAPEX_ELEVATOR_MECHANICAL_COST = 150_000;
export const CAPEX_ROOF_EXTERIOR_COST = 200_000;
export const CAPEX_FB_EQUIPMENT_COST = 100_000;
export const CAPEX_SPA_EQUIPMENT_COST = 75_000;

export const CAPEX_SOFT_GOODS_PER_KEY = 8_000;
export const CAPEX_CASE_GOODS_PER_KEY = 12_000;
export const CAPEX_HVAC_PER_KEY = 5_000;
export const CAPEX_TECH_PER_KEY = 2_000;

export const CAPEX_SOFT_GOODS_LIFE_YEARS = 5;
export const CAPEX_CASE_GOODS_LIFE_YEARS = 10;
export const CAPEX_HVAC_LIFE_YEARS = 15;
export const CAPEX_STRUCTURAL_LIFE_YEARS = 20;
export const CAPEX_TECH_LIFE_YEARS = 5;
export const CAPEX_FB_EQUIPMENT_LIFE_YEARS = 8;
export const CAPEX_SPA_EQUIPMENT_LIFE_YEARS = 7;

export const CAPEX_INDUSTRY_BENCHMARK_PER_KEY = 5_000;
