export type { IconProps } from '@phosphor-icons/react';

export * from './navigation-icons';
export * from './financial-icons';
export * from './status-icons';
export * from './media-icons';
export * from './action-icons';
export * from './data-display-icons';
export * from './misc-icons';

import { IconAudioLines, IconCamera, IconMic, IconPause, IconPhone, IconPhoneOff, IconPlay, IconSend } from './media-icons';
import { IconBarChart3, IconCreditCard, IconTrendingDown, IconTrendingUp } from './financial-icons';
import { IconBell, IconCheck, IconCheckCircle2, IconCheckCircle, IconHelpCircle, IconLoader, IconSettings, IconX } from './status-icons';
import { IconClipboardList, IconCode, IconDatabase, IconFileCode, IconFile, IconFileText, IconFolder, IconTerminal } from './data-display-icons';
import { IconChevronDown, IconChevronLeft, IconChevronRight, IconChevronUp, IconColumns, IconArrowDown, IconArrowUp, IconLayoutDashboard, IconList, IconLogOut, IconMoreVertical } from './navigation-icons';
import { IconCopy, IconFilter, IconLock, IconMail, IconMoreHorizontal, IconPin, IconPlus, IconPlusCircle, IconSearch, IconShare, IconUnlock } from './action-icons';
import { IconAlignLeft, IconFlag, IconGripVertical, IconSquare, IconTrophy } from './misc-icons';
import { IconUserCircle, IconUsers } from './misc-icons';

export const IconAudioLinesIcon = IconAudioLines;
export const IconBarChartIcon = IconBarChart3;
export const IconBellIcon = IconBell;
export const IconCameraIcon = IconCamera;
export const IconCheckIcon = IconCheck;
export const IconCheckCircle2Icon = IconCheckCircle2;
export const IconCheckCircleIcon = IconCheckCircle;
export const IconXIcon = IconX;
export const IconClipboardListIcon = IconClipboardList;
export const IconCodeIcon = IconCode;
export const IconColumnsIcon = IconColumns;
export const IconCopyIcon = IconCopy;
export const IconCreditCardIcon = IconCreditCard;
export const IconDatabaseIcon = IconDatabase;
export const IconFileCodeIcon = IconFileCode;
export const IconFileIcon = IconFile;
export const IconFileTextIcon = IconFileText;
export const IconFilterIcon = IconFilter;
export const IconFlagIcon = IconFlag;
export const IconFolderIcon = IconFolder;
export const IconGripVerticalIcon = IconGripVertical;
export const IconHelpCircleIcon = IconHelpCircle;
export const IconLayoutDashboardIcon = IconLayoutDashboard;
export const IconListIcon = IconList;
export const IconLoaderIcon = IconLoader;
export const IconLockIcon = IconLock;
export const IconLogOutIcon = IconLogOut;
export const IconMailIcon = IconMail;
export const IconMicIcon = IconMic;
export const IconMoreHorizontalIcon = IconMoreHorizontal;
export const IconMoreVerticalIcon = IconMoreVertical;
export const IconPauseIcon = IconPause;
export const IconPhoneIcon = IconPhone;
export const IconPhoneOffIcon = IconPhoneOff;
export const IconPinIcon = IconPin;
export const IconPlayIcon = IconPlay;
export const IconPlusCircleIcon = IconPlusCircle;
export const IconPlusIcon = IconPlus;
export const IconSearchIcon = IconSearch;
export const IconSendIcon = IconSend;
export const IconSettingsIcon = IconSettings;
export const IconShareIcon = IconShare;
export const IconSquareIcon = IconSquare;
export const IconTerminalIcon = IconTerminal;
export const IconTrendingDownIcon = IconTrendingDown;
export const IconTrendingUpIcon = IconTrendingUp;
export const IconTrophyIcon = IconTrophy;
export const IconUnlockIcon = IconUnlock;
export const IconUserCircleIcon = IconUserCircle;
export const IconUsersIcon = IconUsers;
export const IconChevronDownIcon = IconChevronDown;
export const IconChevronUpIcon = IconChevronUp;
export const IconChevronLeftIcon = IconChevronLeft;
export const IconChevronRightIcon = IconChevronRight;
export const IconArrowDownIcon = IconArrowDown;
export const IconArrowUpIcon = IconArrowUp;
export const IconAlignLeftIcon = IconAlignLeft;
