export {
  Flask as IconResearch,
  UsersThree as IconPeople,
  UserGear as IconUserCog,
  User as IconUser,
  Users as IconUsers,
  UserCircle as IconUserCircle,
  TextT as IconType,
  Square as IconSquare,
  PaintBrush as IconPaintbrush,
  Bathtub as IconBath,
  ForkKnife as IconUtensilsCrossed,
  Waves as IconWaves,
  Tree as IconTrees,
  Flask as IconFlaskConical,
  Translate as IconLanguages,
  Ruler as IconRuler,
  CursorClick as IconMousePointerClick,
  DotsSixVertical as IconGripVertical,
  Flag as IconFlag,
  Trophy as IconTrophy,
  AlignLeft as IconAlignLeft,
  IconContext,
} from "@phosphor-icons/react";
