export type { Icon as LucideIcon, IconProps } from "@phosphor-icons/react";

export {
  Warning as AlertTriangle,
  AlignLeft,
  Archive,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowsDownUp as ArrowUpDown,
  Bell,
  BookOpen,
  Buildings as Building2,
  Calculator,
  Check,
  CheckSquare,
  Cloud,
  CaretDoubleLeft as ChevronsLeft,
  CaretDoubleRight as ChevronsRight,
  DownloadSimple as Download,
  CheckCircle,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUpDown as ChevronsUpDown,
  CaretUp as ChevronUp,
  Circle,
  Clock,
  Crop,
  Diamond,
  ArrowSquareOut as ExternalLink,
  Flag,
  GearSix as Gear,
  Flask as FlaskConical,
  FolderOpen as FolderInput,
  Images as GalleryHorizontal,
  Images as GalleryVerticalEnd,
  GitDiff as GitCompare,
  DotsSixVertical as GripVertical,
  Hourglass,
  Image as ImageIcon,
  Image as ImagePlus,
  Images,
  Info,
  Lightbulb,
  SpinnerGap as Loader2,
  Lock,
  Envelope as Mail,
  ChatCircle as MessageCircle,
  Chat as MessageSquare,
  Minus,
  Moon,
  DotsThree as MoreHorizontal,
  DotsThreeVertical as MoreVertical,
  SidebarSimple as PanelLeft,
  ArrowLineRight as PanelRightClose,
  Paperclip,
  PencilSimple as Pencil,
  Phone,
  PhoneDisconnect as PhoneOff,
  Plus,
  ArrowCounterClockwise as RotateCcw,
  Scales as Scale,
  MagnifyingGlass as Search,
  PaperPlaneRight as Send,
  HardDrives as Server,
  ShareNetwork as Share2,
  Shield,
  Sparkle as Sparkles,
  NotePencil as SquarePen,
  SkipForward,
  Star,
  Sun,
  Trash as Trash2,
  Warning as TriangleAlert,
  Trophy,
  ArrowClockwise as RefreshCw,
  FileText,
  ArrowCounterClockwise as Undo2,
  UploadSimple as Upload,
  X,
  XCircle,
  MagnifyingGlassPlus as ZoomIn,
  MagnifyingGlassMinus as ZoomOut,
} from "@phosphor-icons/react";

// Named aliases for shadcn/ui compatibility
export {
  ArrowDown as ArrowDownIcon,
  ArrowUp as ArrowUpIcon,
  Check as CheckIcon,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRightIcon,
  CaretDoubleLeft as ChevronsLeftIcon,
  CaretDoubleRight as ChevronsRightIcon,
  DotsSixVertical as GripVerticalIcon,
  SpinnerGap as Loader2Icon,
  SpinnerGap as LoaderIcon,
  DotsThree as MoreHorizontalIcon,
  DotsThreeVertical as MoreVerticalIcon,
  Phone as PhoneIcon,
  X as XIcon,
} from "@phosphor-icons/react";
